package nslm2.inits
{
   import com.mz.core.utils2.task.TaskBase;
   import nslm2.modules.footstones.moduleBases.ModuleMgr;
   import nslm2.modules.footstones.moduleBases.ModuleConfigVo;
   import nslm2.modules.footstones.resGetPoints.ResGetPointModule;
   import nslm2.modules.foundations.alerts.HelpAndRulePanel;
   import nslm2.modules.foundations.alerts.NewVersionModule;
   import nslm2.modules.foundations.setting.SettingModule;
   import nslm2.modules.footstones.alerts.FPSLowlyAlert;
   import nslm2.modules.foundations.vip.QQChargeModule;
   import com.mz.core.mgrs.resMgrs.ResVo;
   import nslm2.modules.footstones.loadingModules.UrlLib;
   import nslm2.modules.funnies.tencent.QQWeiDuanGiftModule;
   import nslm2.modules.foundations.vip.VipModule;
   import com.mz.core.configs.EnvConfig;
   import nslm2.modules.funnies.renZhengs.vipAuths.RenZhengVipModule;
   import nslm2.modules.funnies.renZhengs.vipAuths.VipAuthXunLeiModule;
   import nslm2.modules.foundations.vipLvlUp.VipLvlUpModule;
   import nslm2.modules.funnies.newYears.newYear2016s.NewYear2016Module;
   import nslm2.modules.funnies.newYears.valentine2016.Valentine2016Module;
   import nslm2.modules.funnies.newYears.lantern2016.Lantern2016Module;
   import nslm2.modules.funnies.newYears.valentine2016.ValentineBuyConfirmModule;
   import nslm2.modules.funnies.newYears.lantern2016.LanternBuyConfirmModule;
   import nslm2.modules.funnies.newYears.valentine2016.ValentineSendFlowerModule;
   import nslm2.modules.foundations.monthlyCard.MonthlyCardModule;
   import nslm2.modules.foundations.alerts.views.RechargeAlert;
   import nslm2.modules.foundations.worldMap.WorldMapModule;
   import nslm2.modules.foundations.gameMaster.GameMasterModule;
   import nslm2.modules.foundations.gameHelp.GameHelpModule;
   import nslm2.modules.foundations.sales.SalesModule;
   import nslm2.modules.foundations.fund.FundModule;
   import nslm2.modules.funnies.tencent.TencentVipModule;
   import nslm2.modules.funnies.playerTitles.PlayerTitleModule;
   import nslm2.modules.funnies.tencent.TencentRenewalModule;
   import nslm2.modules.funnies.qihoo.QihooModule;
   import nslm2.modules.funnies.sogou.SogouModule;
   import nslm2.modules.funnies.renZhengs.WeiXinAndPhones.WeiXinAndPhoneModule;
   import nslm2.modules.funnies.renZhengs.WeiXinAndPhones.RenZhengXunLeiPhoneModule;
   import nslm2.modules.foundations.activities.ActivityForeshow;
   import nslm2.modules.funnies.xunleiGifts.XunleiGiftModule;
   import nslm2.modules.foundations.firstCharge.FirstChargeView;
   import nslm2.modules.foundations.firstCharge.chargeTips.ChargeTipModule;
   import nslm2.modules.foundations.miniApp.MiniAppModule1;
   import nslm2.modules.foundations.favorite.FavoriteModule;
   import nslm2.modules.foundations.sevenDays.SevenDaysModule;
   import nslm2.modules.foundations.sevenDays.SevenDayBuyConfirmModule;
   import nslm2.modules.foundations.fourteenDays.FourteenDaysModule;
   import nslm2.modules.foundations.fourteenDays.FouteenDayBuyComfirmModule;
   import nslm2.modules.footstones.driverInfoModules.DriverInfoModule;
   import nslm2.modules.footstones.linkModules.LinkModule;
   import nslm2.modules.foundations.miniMaps.MiniMap;
   import nslm2.modules.foundations.miniMaps.BattlefieldMiniMap;
   import nslm2.modules.foundations.miniMaps.PeakSportsMiniMap;
   import nslm2.modules.foundations.miniTasks.MiniTask;
   import nslm2.modules.foundations.miniTasks.view.TaskInfoPanel;
   import nslm2.modules.foundations.mainToolBar.TopIconModule;
   import nslm2.modules.foundations.playerHeaders.PlayerHeader;
   import nslm2.modules.foundations.miniNotice.MiniNoticeModule;
   import nslm2.modules.foundations.chatModules.ChatModule;
   import nslm2.modules.foundations.chatModules.privChats.PrivChatModule;
   import nslm2.modules.foundations.chatModules.localChatHistory.LocalChatHistory;
   import nslm2.modules.footstones.notices.BottomMsgModule;
   import nslm2.modules.foundations.mainToolBar.MainBottomIconModule;
   import nslm2.modules.cultivates.lotteryHeroModules.LotteryHeroModule;
   import nslm2.modules.footstones.assistantModules.AssistantModule;
   import nslm2.modules.footstones.newOpenFuncModules.NewOpenFuncMiniModule;
   import nslm2.modules.footstones.newOpenFuncModules.NewOpenFuncModule;
   import nslm2.modules.cultivates.lotteryHeroModules.getRewards.LotteryHeroGetRewardModule;
   import nslm2.modules.bag.UseHeroSelectBoxView;
   import nslm2.modules.cultivates.lotteryHeroModules.heroPreviews.HeroPreviewModule;
   import nslm2.modules.funnies.newYears.day38s.Day38Module;
   import nslm2.modules.funnies.newYears.day38s.Day38_GiftPanel;
   import nslm2.modules.funnies.newYears.day38s.Day38_ResultPanel;
   import nslm2.modules.cultivates.heroBag.HeroPieceActiveSuccess;
   import nslm2.modules.battles.pvp.PvpBattleModule;
   import nslm2.modules.battles.BattleTestModule;
   import nslm2.modules.battles.reportPlayer.BattleReportModule;
   import nslm2.modules.battles.pvp.PlayerPKModule;
   import nslm2.modules.battles.reportPlayer.BattleReportTestModule;
   import nslm2.modules.logModules.LogModule;
   import nslm2.modules.logModules.GMCmdModule;
   import nslm2.modules.logModules.TestModule;
   import nslm2.modules.logModules.TestModule1;
   import nslm2.modules.logModules.TestModule2;
   import nslm2.modules.logModules.TestModule3;
   import nslm2.modules.footstones.tooltipsModules.TooltipModule;
   import nslm2.modules.battles.battleResults.BattleWinModule;
   import nslm2.modules.battles.battleResults.battleLoss.BattleLossModule;
   import nslm2.modules.battles.battleStatistic.BattleStatisticModule;
   import nslm2.modules.battles.battleResults.BattleWinArenaModule;
   import nslm2.modules.funnies.pkCrossSer.PKCrossComp.PKCrossResultModule;
   import nslm2.modules.battles.battleResults.BattleCompleteModule;
   import nslm2.modules.battles.battlefields.BattlefieldModule;
   import nslm2.modules.battles.battlefields.BattlefieldTeamModule;
   import nslm2.modules.battles.battlefields.BattlefieldInvitedModule;
   import nslm2.modules.battles.battlefields.BattlefieldIntroduceModule;
   import nslm2.modules.battles.battlefields.BattlefieldTodayRewardModule;
   import nslm2.modules.battles.battlefields.BattlefieldRankModule;
   import nslm2.modules.battles.battlefields.BattlefieldRankRewardModule;
   import nslm2.modules.battles.battlefields.BattlefieldReportModule;
   import nslm2.modules.battles.battlefields.BattlefieldFightResultModule;
   import nslm2.modules.battles.battlefields.scene.BattlefieldSceneModule;
   import nslm2.modules.footstones.tipMenus.TipMenuModule;
   import nslm2.modules.scenes.shenYuans.ShenYuanModule;
   import nslm2.modules.battles.shenYuanBattle.ShenYuanBattleModule;
   import nslm2.modules.scenes.shenYuans.comp.SYLuckRewardModule;
   import nslm2.modules.scenes.shenYuans.comp.ShenYuanHelpPanel;
   import nslm2.modules.funnies.mainCities.TestSceneModule;
   import nslm2.modules.funnies.mainCities.MainCityModule;
   import nslm2.modules.Chapters.DungeonMapModule;
   import nslm2.modules.Chapters.treasureBox.TreasureBoxModule;
   import nslm2.modules.Chapters.elite.EliteInvadeModule;
   import nslm2.modules.Chapters.elite.EliteInvadeInfoPanel;
   import nslm2.modules.Chapters.DungeonInfoPanel;
   import nslm2.modules.dungeons.DungeonSceneModule;
   import nslm2.modules.fightPlayer.FightSceneModule;
   import nslm2.modules.battles.resourceDungeons.ResourceDungeonModule;
   import nslm2.modules.funnies.newYears.newYear2016s.bossPanels.NewYear2016BossFightModule;
   import nslm2.modules.Chapters.elite.EliteInvadeSceneModule;
   import nslm2.modules.funnies.teamGuajiScenes.subpalaceBoss.SubpalaceBossFightModule;
   import nslm2.modules.cultivates.reinforceTrain.ReinforceTrainModule;
   import nslm2.modules.fightPlayer.TestScene3DModule7;
   import nslm2.modules.foundations.friendModules.FriendModule;
   import nslm2.modules.foundations.friendModules.searches.FriendSearchOneModule;
   import nslm2.modules.foundations.friendModules.searches.FriendRecommendModule;
   import nslm2.modules.foundations.friendModules.searches.FriendApplyModule;
   import nslm2.modules.foundations.friendModules.activities.FriendGiftModule;
   import nslm2.modules.foundations.friendModules.activities.FriendLogModule;
   import nslm2.modules.foundations.mail.FmailMainModule;
   import nslm2.modules.foundations.mail.ReadMailPanel;
   import nslm2.modules.foundations.mail.WriteMailPanel;
   import nslm2.modules.roleInfos.RoleInfoModule;
   import nslm2.modules.roleInfos.tupos.RoleTupoSuccessModule;
   import nslm2.modules.roleInfos.tupos.RoleTupoGodhoodModule;
   import nslm2.modules.roleInfos.tupos.RoleTupoConfirmModule;
   import nslm2.modules.roleInfos.awake.RoleAwakeEquipFullModule;
   import nslm2.modules.roleInfos.phaseUps.RoleShenjieTujianPanel;
   import nslm2.modules.roleInfos.phaseUps.RoleShenjieSuccessPanel;
   import nslm2.modules.cultivates.equipGrows.EquipGrowModule;
   import nslm2.modules.cultivates.horse.HorseMainModule;
   import nslm2.modules.cultivates.horse.horseMaster.HorseShengjieCplModule;
   import nslm2.modules.cultivates.militaryInfos.MilitaryModule;
   import nslm2.modules.cultivates.fashion.FashionModule;
   import nslm2.modules.cultivates.skin.SkinModule;
   import nslm2.modules.cultivates.skin.SkinBookModule;
   import nslm2.modules.cultivates.treasure.TreasureFuwenKeyinCplModule;
   import nslm2.modules.bag.BagModule;
   import nslm2.modules.bag.equipComposes.EquipCompose;
   import nslm2.modules.foundations.activities.ActivityExchange;
   import nslm2.modules.bag.UseBatchView;
   import nslm2.modules.bag.YIYEView;
   import nslm2.modules.cultivates.heroBag.HeroShowModule;
   import nslm2.modules.foundations.guildModule.view.panel.shardDonate.GuildHeroShardListModule;
   import nslm2.modules.foundations.signIn.FSignInModule;
   import nslm2.modules.cultivates.roleTeam.RoleTeamModule;
   import nslm2.modules.cultivates.roleTeam.view.panel.equipMaster.EquipMasterPanel;
   import nslm2.modules.cultivates.treasure.TreasureModule;
   import nslm2.modules.cultivates.treasure.view.SelectTreasurePanel;
   import nslm2.modules.cultivates.treasure.view.compose.RuneComposePanel;
   import nslm2.modules.cultivates.treasure.view.compose.RuneBatchCompsePanel;
   import nslm2.modules.cultivates.treasure.view.compose.RuneBatchComposePreviewPanel;
   import nslm2.modules.cultivates.treasure.view.compose.RuneBatchComposeSuccessPanel;
   import nslm2.modules.roleInfos.phaseUps.talents.PhaseUpTalentPanel;
   import nslm2.modules.cultivates.otherRoleInfos.OtherRoleInfoModule;
   import nslm2.modules.cultivates.otherRoleInfos.heroCompare.HCModule;
   import nslm2.modules.cultivates.otherRoleInfos.heroCompare.HCSelectHeroPanel;
   import nslm2.modules.funnies.teamPKCS.TeamPKCModule;
   import nslm2.modules.funnies.teamPKCS.TPKCChangeOrder;
   import nslm2.modules.funnies.teamPKCS.rank.TPKCRankModule;
   import nslm2.modules.funnies.teamPKCS.report.TPKCReportPanel;
   import nslm2.modules.funnies.teamPKCS.invite.TPKCInviteList;
   import nslm2.modules.funnies.teamPKCS.TPKWinnerShowModule;
   import nslm2.modules.funnies.teamPKCS.finalMatch.TPKCGambleModule;
   import nslm2.modules.funnies.teamPKCS.finalMatch.TPKCMyGamblePanel;
   import nslm2.modules.funnies.teamPKCS.rank.TPKCRankRewardModule;
   import nslm2.modules.funnies.teamPKCS.intros.TPKIntroPanel;
   import nslm2.modules.footstones.alerts.FloadMsgModule;
   import nslm2.modules.footstones.alerts.EventNoticeModule;
   import nslm2.modules.footstones.alerts.MsgTopCenterModule;
   import nslm2.modules.footstones.newerAlertModules.NewerAlertModule;
   import nslm2.modules.footstones.quickUseModules.QuickUseModule;
   import nslm2.modules.footstones.newerFunctionOpen.NewerFunctionOpen;
   import nslm2.modules.foundations.alerts.views.SimpleAlert;
   import nslm2.modules.footstones.pwdModules.PwdModule;
   import nslm2.modules.cultivates.position.PositionModule;
   import nslm2.modules.foundations.ranks.RankModule;
   import nslm2.modules.funnies.pkCrossSer.PKCrossComp.PKCrossRankModule;
   import nslm2.modules.funnies.pkCrossSer.WinnerShowModule;
   import nslm2.modules.foundations.shop.MysteryShopModule;
   import nslm2.modules.foundations.shop.ShopBuyModule;
   import nslm2.modules.foundations.shop.ShopModule;
   import nslm2.modules.foundations.activities.ActivityModule;
   import nslm2.modules.cultivates.recommendHero.RecommendHeroModule;
   import nslm2.modules.cultivates.skillChangePanels.SkillChangeModule;
   import nslm2.modules.footstones.loadingModules.LoadingModule;
   import nslm2.modules.footstones.newerGuideModules.NewerGuideModule;
   import nslm2.modules.foundations.dailyTask.DailyTaskModule;
   import nslm2.modules.foundations.heroChoose.HeroChooseModule;
   import nslm2.modules.foundations.recycle.RecycleModule;
   import nslm2.modules.foundations.recycle.view.panel.heroRec.RecSelectHeroPanel;
   import nslm2.modules.foundations.recycle.view.panel.equipRec.RecSelectEquiipPanel;
   import nslm2.modules.foundations.recycle.view.panel.RecycleConfirmPanel;
   import nslm2.modules.foundations.recycle.view.panel.heroReborn.RecSelectRebornHeroPanel;
   import nslm2.modules.foundations.recycle.view.panel.treasureReborn.RecSelectRebornTreasurePanel;
   import nslm2.modules.foundations.recycle.view.panel.treasureRec.RecSelectRecTreasurePanel;
   import nslm2.modules.foundations.recycle.view.panel.heroMirror.HeroMirrorSelectHeroPanel;
   import nslm2.modules.foundations.recycle.view.panel.petReborn.RecSelectRebornPetPanel;
   import nslm2.modules.foundations.guildModule.GuildModule;
   import nslm2.modules.foundations.guildModule.view.panel.appoint.GuildAppointPanel;
   import nslm2.modules.foundations.guildModule.view.panel.verify.GuildVerifyPanel;
   import nslm2.modules.foundations.guildModule.view.panel.donate.GuildDonatePanel;
   import nslm2.modules.foundations.guildModule.view.panel.GuildUpgradePanel;
   import nslm2.modules.foundations.guildModule.view.panel.GuildChangeNoticePanel;
   import nslm2.modules.foundations.guildModule.view.panel.CreateGuildPanel;
   import nslm2.modules.foundations.guildModule.view.panel.log.GuildLogPanel;
   import nslm2.modules.foundations.guildModule.view.panel.flag.GuildFlagPanel;
   import nslm2.modules.foundations.guildModule.view.panel.rank.GuildDetialInfoPanel;
   import nslm2.modules.foundations.guildModule.view.panel.setAuth.SetAuthrorityPanel;
   import nslm2.modules.foundations.guildModule.view.panel.guildList.GuildListPanel;
   import nslm2.modules.foundations.guildModule.view.panel.invite.GuildInviteFriendPanel;
   import nslm2.modules.funnies.guilds.guildTechs.GuildTechModule;
   import nslm2.modules.funnies.guilds.guildTechs.GuildTechResearchModule;
   import nslm2.modules.battles.guildDungeons.GuildDungeonModule;
   import nslm2.modules.battles.guildDungeons.GuildDungeonSceneModule;
   import nslm2.modules.battles.guildDungeons.GuildDungeonYukouSceneModule;
   import nslm2.modules.battles.guildDungeons.GuildDungeonTargetModule;
   import nslm2.modules.battles.guildDungeons.GuildDungeonTreasureModule;
   import nslm2.modules.battles.guildDungeons.GuildDungeonVideoPanel;
   import nslm2.modules.funnies.families.familyBosses.FamilyBossModule;
   import nslm2.modules.funnies.families.familyBosses.FamilyBossFightModule;
   import nslm2.modules.funnies.families.familyBosses.view.FamilyBossSetTimeModule;
   import nslm2.modules.funnies.families.familyBosses.view.FamilyBossDmgRewardModule;
   import nslm2.modules.funnies.families.familyBosses.view.FamilyBossHornorRankModule;
   import nslm2.modules.funnies.npcFuncLists.NpcFuncListModule;
   import nslm2.modules.funnies.funnyEvents.FunnyEventModule;
   import nslm2.modules.funnies.pkCrossSer.PKCrossComp.PKCrossCheerModule;
   import nslm2.modules.funnies.pkCrossSer.PKCrossComp.PKCrossReportModule;
   import nslm2.modules.funnies.pkCrossSer.PKCrossModule;
   import nslm2.modules.funnies.guildPKCrossSer.GPKCrossModule;
   import nslm2.modules.funnies.guildPKCrossSer.comp.GPKStartPanel;
   import nslm2.modules.funnies.guildPKCrossSer.quest.GPKQuestPanel;
   import nslm2.modules.funnies.guildPKCrossSer.lottery.GPKLotteryPanel;
   import nslm2.modules.funnies.guildPKCrossSer.skill.GPKSkillPanel;
   import nslm2.modules.funnies.guildPKCrossSer.report.GPKReportModule;
   import nslm2.modules.funnies.guildPKCrossSer.rank.GPKRankModule;
   import nslm2.modules.funnies.guildPKCrossSer.skill.GPKSkillRankPanel;
   import nslm2.modules.funnies.guildPKCrossSer.GPKWinnerShowModule;
   import nslm2.modules.funnies.guildPKCrossSer.rank.GPKRankReward;
   import nslm2.modules.funnies.guildPKCrossSer.GPKChallReward;
   import nslm2.modules.funnies.guildPKCrossSer.GPKIntroPanel;
   import nslm2.modules.funnies.arenas.ArenaModule;
   import nslm2.modules.funnies.arenas.rewards.ArenaRewardModule;
   import nslm2.modules.funnies.arenas.ranks.ArenaRankModule;
   import nslm2.modules.funnies.arenas.scores.ArenaScoreModule;
   import nslm2.modules.funnies.arenas.mains.ArenaBattleResultModule;
   import nslm2.modules.funnies.championShip.ChampionShipModule;
   import nslm2.modules.funnies.championShip.view.ChampionGamblePanel;
   import nslm2.modules.funnies.championShip.view.ChampionRewardPanel;
   import nslm2.modules.funnies.championShip.view.ChampionGambleRecordPanel;
   import nslm2.modules.funnies.championShip.view.ChampionshipCompeteRecordPanel;
   import nslm2.modules.funnies.teams.listModules.TeamListModule;
   import nslm2.modules.funnies.teams.details.TeamDetailModule;
   import nslm2.modules.funnies.teams.details.TeamApplyList;
   import nslm2.modules.funnies.teamGuajiScenes.TeamGuajiScene;
   import nslm2.modules.funnies.teamGuajiScenes.changeChallenges.GuajiChangeChallengeModule;
   import nslm2.modules.funnies.teamGuajiScenes.guajiFunctions.guajiBag;
   import nslm2.modules.funnies.teams.details.TeamInviteFriendModule;
   import nslm2.modules.funnies.teamGuajiScenes.pvp.pieceBag.TreasurePieceBagModule;
   import nslm2.modules.funnies.teamGuajiScenes.pvp.pieceBag.TreasureComposeModule;
   import nslm2.modules.funnies.teamGuajiScenes.pvp.RobTreasurePieceModule;
   import nslm2.modules.funnies.teamGuajiScenes.pvp.rank.TeamGuajiRankModule;
   import nslm2.modules.funnies.teamGuajiScenes.pvp.TeamGuajiPvPFightModule;
   import nslm2.modules.funnies.teamGuajiScenes.mini.TeamGuajiMiniPanel;
   import nslm2.modules.foundations.noticeModule.NoticeModule;
   import nslm2.modules.footstones.roleLvlUpModule.RoleLvlUpModule;
   import nslm2.modules.footstones.seePlayerModule.SeePlayerModule;
   import nslm2.modules.foundations.mall.MallModule;
   import nslm2.modules.foundations.mall.MallBuyConfirmModule;
   import nslm2.modules.foundations.mall.view.MallAlertModule;
   import nslm2.modules.footstones.getItemsDisplayModule.GetItemsDisplayModule;
   import nslm2.modules.funnies.gifts.ExchangeModule;
   import nslm2.modules.foundations.auctionShop.AuctionShopModule;
   import nslm2.modules.foundations.auctionShop.view.AuctionSellItemPanel;
   import nslm2.modules.foundations.auctionShop.view.AuctionBuyItemPanel;
   import nslm2.modules.funnies.abilityRankModule.AbilityRankModule;
   import nslm2.modules.battles.heroAwakenRoad.HeroAwakenRoadModule;
   import nslm2.modules.battles.heroAwakenRoad.HeroAwakenRoadFightModule;
   import nslm2.modules.globalModules.facebook.FBInviteViewModule;
   import nslm2.modules.globalModules.facebook.view.FBShareModule;
   import nslm2.modules.globalModules.resRecovery.view.ResRecoveryModule;
   import nslm2.modules.globalModules.fbFansPage.FBFansPageModule;
   import nslm2.modules.funnies.worldBoss.WorldBossModule;
   import nslm2.modules.funnies.worldBoss.view.WorldBossRankModule;
   import nslm2.modules.funnies.groupon.GrouponModule;
   import nslm2.modules.funnies.groupon.view.GrouponBuyItemConfirmModule;
   import nslm2.modules.funnies.newYears.charmStar.CharmStarModule;
   import nslm2.modules.bag.UseGiftView;
   import nslm2.modules.funnies.newYears.charmStar.view.CharmStarUseCocoConfirmModule;
   import nslm2.modules.funnies.newYears.charmStar.view.CharmStarBuyConfirmModule;
   import nslm2.modules.funnies.dials.DialModule;
   import nslm2.modules.foundations.angelFund.AngelFundModule;
   import nslm2.modules.funnies.newYears.luckTrees.LuckTreeModule;
   import nslm2.modules.funnies.newYears.day51s.Day51Module;
   import nslm2.modules.funnies.newYears.day51s.panels.Day51HelpModule;
   import nslm2.modules.foundations.goldenShopModules.GoldenDiamondChangeModule;
   import nslm2.modules.cultivates.fashionAcc.FashionAccModule;
   import nslm2.modules.cultivates.fashionAcc.FashionAccSelectModule;
   import nslm2.modules.foundations.shop.MysteryShopHeroShardListModule;
   import nslm2.modules.cultivates.fashionAcc.FashionAccSkillWindow;
   import nslm2.modules.funnies.newYears.fooldays.Foolday2016Module;
   import nslm2.modules.cultivates.pet.PetModule;
   import nslm2.modules.cultivates.pet.view.panel.PetStarPreViewPanel;
   import nslm2.modules.cultivates.pet.PetSelectModule;
   import nslm2.modules.cultivates.pet.PetSkinModule;
   import nslm2.modules.funnies.secretExplore.SecretExploreModule;
   import nslm2.modules.funnies.secretExplore.SEHelpPanel;
   import nslm2.modules.funnies.secretExplore.SEAssistRank;
   import nslm2.modules.funnies.secretExplore.SEScoreModule;
   import nslm2.modules.funnies.secretExplore.SEBattleModule;
   import nslm2.modules.funnies.newYears.olmpic2016.OlmpicSelCountryModule;
   import nslm2.modules.battles.PeakSports.view.PeakSportsModule;
   import nslm2.modules.battles.PeakSports.view.PeakSportsRewardModule;
   import nslm2.modules.battles.PeakSports.view.PeakSportsIntroduceModule;
   import nslm2.modules.battles.PeakSports.view.PeakSportsReportModule;
   import nslm2.modules.battles.PeakSports.scene.PeakSportsSceneModule;
   import nslm2.modules.battles.PeakSports.view.PeakSportsFightResultModule;
   import nslm2.modules.funnies.busyActivity.towers.TowerModule;
   import nslm2.modules.funnies.busyActivity.questions.QuestionModule;
   import nslm2.modules.funnies.busyActivity.dragonBoats.DragonBoatModule;
   import nslm2.modules.funnies.busyActivity.dragonBoats.others.DragonBoatHelpModule;
   import nslm2.modules.funnies.busyActivity.dragonBoats.funnys.DragonBoatFunnyMakeConfirm;
   import nslm2.modules.funnies.busyActivity.dragonBoats.donates.DragonBoatDonateConfirm;
   import nslm2.modules.funnies.busyActivity.dragonBoats.donates.DragonBoatDonateRequestPanel;
   import com.mz.core.configs.ClientConfig;
   import com.mz.core.mgrs.UIMgr;
   import nslm2.common.ui.components.comps2d.MainBlackRim;
   import flash.events.Event;
   
   public class RegModuleTask extends TaskBase
   {
       
      
      public function RegModuleTask()
      {
         super();
      }
      
      override public function exec() : void
      {
         var _loc1_:* = null;
         super.exec();
         ModuleMgr.ins.regModule(new ModuleConfigVo(12101,3,ResGetPointModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(12201,3,HelpAndRulePanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(96050,3,NewVersionModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10900,3,SettingModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10910,4,FPSLowlyAlert));
         ModuleMgr.ins.regModule(new ModuleConfigVo(60723,3,QQChargeModule,[new ResVo("ui/uiVip.uibaz"),new ResVo(UrlLib.getTencentImg("chargeRim")),new ResVo(UrlLib.getTencentImg("img_backpanel"))]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(60730,3,QQWeiDuanGiftModule,[new ResVo("ui/uiQQWeiDuanGift.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10800,3,VipModule,[new ResVo("ui/uiVip.uibaz")]));
         if(EnvConfig.ins.ptId == 590 || EnvConfig.ins.ptId == 82)
         {
            ModuleMgr.ins.regModule(new ModuleConfigVo(60600,3,RenZhengVipModule,[new ResVo("ui/uiRenZhengVips.uibaz")]));
         }
         else
         {
            ModuleMgr.ins.regModule(new ModuleConfigVo(60600,3,VipAuthXunLeiModule,[new ResVo("ui/uiVipAuthShunWang.uibaz")]));
         }
         ModuleMgr.ins.regModule(new ModuleConfigVo(12100,3,VipLvlUpModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13310,3,NewYear2016Module,[new ResVo("ui/uiNewYear2016.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13320,3,Valentine2016Module,[new ResVo("ui/uiValentine2016.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13330,3,Lantern2016Module,[new ResVo("ui/uiLantern2016.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13322,3,ValentineBuyConfirmModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13331,3,LanternBuyConfirmModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13321,3,ValentineSendFlowerModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(60530,3,MonthlyCardModule,[new ResVo("ui/uiMonthlyCard.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10101,3,RechargeAlert));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10450,3,WorldMapModule,[new ResVo("ui/uiWorldMap.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13200,3,GameMasterModule,[new ResVo("ui/uiGameMaster.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13201,3,GameHelpModule,[new ResVo("ui/uiGameHelp.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(60540,3,SalesModule,[new ResVo("ui/uiSales.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(60100,3,FundModule,[new ResVo("ui/uiFund.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(60710,3,TencentVipModule,[new ResVo("ui/uiTencent.uibaz"),new ResVo("ui/uiYellowVip.uibaz"),new ResVo("ui/uiBlueVip.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30900,3,PlayerTitleModule,[new ResVo("ui/uiPlayerTitle.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(60721,3,TencentRenewalModule,[new ResVo("ui/uiTencent.uibaz"),new ResVo("ui/uiBlueVip.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(60731,3,QihooModule,[new ResVo("ui/uiQihoo.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(60751,3,SogouModule,[new ResVo("ui/uiSogou.uibaz"),new ResVo(UrlLib.getSogouImg("img_bg1"))]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(60752,3,SogouModule,[new ResVo("ui/uiSogou.uibaz"),new ResVo(UrlLib.getSogouImg("img_bg2"))]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(60760,3,WeiXinAndPhoneModule,[new ResVo("ui/uiRenZhengWeiXinAndPhones.uibaz"),new ResVo(UrlLib.renZhengWeiXinAndPhone("img_bg1")),new ResVo(UrlLib.renZhengWeiXinAndPhone("img_bg2")),new ResVo(UrlLib.renZhengWeiXinAndPhone("img_bg3"))]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(60765,3,RenZhengXunLeiPhoneModule,[new ResVo("ui/uiRenZhengWeiXinAndPhones.uibaz"),new ResVo(UrlLib.renZhengWeiXinAndPhone("img_bg1")),new ResVo(UrlLib.renZhengWeiXinAndPhone("img_bg2")),new ResVo(UrlLib.renZhengWeiXinAndPhone("img_bg3"))]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(60777,3,ActivityForeshow,[new ResVo("ui/uiActivityForeshow.uibaz")]));
         _loc1_ = new ModuleConfigVo(60766,3,XunleiGiftModule,[new ResVo("ui/uiXunLeiGift.uibaz"),new ResVo("ui/uiQihoo.uibaz")]);
         ModuleMgr.ins.regModule(new ModuleConfigVo(60766,3,XunleiGiftModule,[new ResVo("ui/uiXunLeiGift.uibaz"),new ResVo("ui/uiQihoo.uibaz")]));
         _loc1_ = new ModuleConfigVo(60200,3,FirstChargeView,[new ResVo("ui/uiFirstCharge.uibaz")]);
         ModuleMgr.ins.regModule(new ModuleConfigVo(60200,3,FirstChargeView,[new ResVo("ui/uiFirstCharge.uibaz")]));
         _loc1_ = new ModuleConfigVo(60210,2,ChargeTipModule,[new ResVo("ui/uiChargeTips.uibaz")]);
         ModuleMgr.ins.regModule(new ModuleConfigVo(60210,2,ChargeTipModule,[new ResVo("ui/uiChargeTips.uibaz")]));
         _loc1_.disposeWhenCloseProxy = 1;
         ModuleMgr.ins.regModule(new ModuleConfigVo(60510,3,MiniAppModule1,[new ResVo("ui/uiMiniApp1.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(60520,3,FavoriteModule,[new ResVo("ui/uiFavorite.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13100,3,SevenDaysModule,[new ResVo("ui/uiSevenDays.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13101,3,SevenDayBuyConfirmModule,[new ResVo("ui/uiSevenDays.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13300,3,FourteenDaysModule,[new ResVo("ui/uiSevenDays.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13301,3,FouteenDayBuyComfirmModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(95400,4,DriverInfoModule,[new ResVo("ui/uiDriverInfoModules.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10300,4,LinkModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10410,2,MiniMap));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10460,2,BattlefieldMiniMap,[new ResVo("ui/uiMiniMap.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10480,2,PeakSportsMiniMap,[new ResVo("ui/uiMiniMap.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10420,2,MiniTask));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10421,3,TaskInfoPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10440,2,TopIconModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10400,2,PlayerHeader));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10470,2,MiniNoticeModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10500,2,ChatModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10540,3,PrivChatModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10550,3,LocalChatHistory));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10120,2,BottomMsgModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10430,2,MainBottomIconModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(11900,2,LotteryHeroModule,[new ResVo("ui/uiLottery.uibaz")]).set_forceShowLoadingType(2).set_noHideLoading(true));
         _loc1_ = new ModuleConfigVo(80100,3,AssistantModule,[new ResVo("ui/uiAssistantModules.uibaz")]);
         ModuleMgr.ins.regModule(new ModuleConfigVo(80100,3,AssistantModule,[new ResVo("ui/uiAssistantModules.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(96600,2,NewOpenFuncMiniModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(96700,4,NewOpenFuncModule));
         _loc1_ = new ModuleConfigVo(11920,3,LotteryHeroGetRewardModule,[new ResVo("ui/uiLuckyReward.uibaz")]);
         ModuleMgr.ins.regModule(new ModuleConfigVo(11920,3,LotteryHeroGetRewardModule,[new ResVo("ui/uiLuckyReward.uibaz")]));
         _loc1_ = new ModuleConfigVo(11921,3,UseHeroSelectBoxView,[new ResVo("ui/uiLuckyReward.uibaz")]);
         ModuleMgr.ins.regModule(new ModuleConfigVo(11921,3,UseHeroSelectBoxView,[new ResVo("ui/uiLuckyReward.uibaz")]));
         _loc1_.useCoverKind = 1;
         ModuleMgr.ins.regModule(new ModuleConfigVo(11930,3,HeroPreviewModule,[new ResVo("ui/uiLottery.uibaz"),new ResVo("ui/uiHeroShow.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13333,3,Day38Module,[new ResVo("ui/uiDay38.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13335,3,Day38_GiftPanel,[new ResVo("ui/uiDay38.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13336,3,Day38_ResultPanel,[new ResVo("ui/uiDay38.uibaz")]));
         _loc1_ = new ModuleConfigVo(30705,3,HeroPieceActiveSuccess,[new ResVo("ui/uiLottery.uibaz")]);
         ModuleMgr.ins.regModule(new ModuleConfigVo(30705,3,HeroPieceActiveSuccess,[new ResVo("ui/uiLottery.uibaz")]));
         _loc1_.useCoverKind = 4;
         ModuleMgr.ins.regModule(new ModuleConfigVo(90200,1,PvpBattleModule,[new ResVo("ui/uiDungeonScene.uibaz"),new ResVo(UrlLib.skillConfigUrl(),10),new ResVo("ui/fightText.swf")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(90201,1,BattleTestModule,[new ResVo("ui/uiDungeonScene.uibaz"),new ResVo(UrlLib.skillConfigUrl(),10),new ResVo("ui/fightText.swf")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40201,1,BattleReportModule,[new ResVo("ui/uiDungeonScene.uibaz"),new ResVo("ui/uiAreanStart.uibaz"),new ResVo(UrlLib.skillConfigUrl(),10),new ResVo("ui/fightText.swf")]).set_loadingAutoAdd(false));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50100,1,PlayerPKModule,[new ResVo("ui/uiDungeonScene.uibaz"),new ResVo("ui/uiAreanStart.uibaz"),new ResVo(UrlLib.skillConfigUrl(),10),new ResVo("ui/fightText.swf")]).set_loadingAutoAdd(false));
         ModuleMgr.ins.regModule(new ModuleConfigVo(99900,1,BattleReportTestModule,[new ResVo("ui/uiDungeonScene.uibaz"),new ResVo(UrlLib.skillConfigUrl(),10),new ResVo("ui/fightText.swf")]).set_loadingAutoAdd(false));
         ModuleMgr.ins.regModule(new ModuleConfigVo(90300,4,LogModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(90315,4,GMCmdModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(90310,3,TestModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(90311,3,TestModule1));
         ModuleMgr.ins.regModule(new ModuleConfigVo(90312,3,TestModule2));
         ModuleMgr.ins.regModule(new ModuleConfigVo(90313,3,TestModule3));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10220,4,TooltipModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40210,3,BattleWinModule,[new ResVo("ui/uiBattleResults.uibaz"),new ResVo("effect2d/battle/dgWinLogo.swf",14)]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40220,3,BattleLossModule,[new ResVo("ui/uiBattleResults.uibaz"),new ResVo("effect2d/battle/lossLogo.swf",14)]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40221,3,BattleStatisticModule,[new ResVo("ui/uiStatistic.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40211,3,BattleWinArenaModule,[new ResVo("ui/uiAreanResults.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50250,3,PKCrossResultModule,[new ResVo("ui/uiAreanResults.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40222,3,BattleCompleteModule,[new ResVo("ui/uiBattleResults.uibaz"),new ResVo("effect2d/battle/dgWinLogo.swf",14)]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50500,3,BattlefieldModule,[new ResVo("ui/uiBattlefields.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50501,3,BattlefieldTeamModule,[new ResVo("ui/uiBattlefields.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50502,3,BattlefieldInvitedModule,[new ResVo("ui/uiBattlefields.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50506,3,BattlefieldIntroduceModule,[new ResVo("ui/uiBattlefields.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50505,3,BattlefieldTodayRewardModule,[new ResVo("ui/uiBattlefields.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50503,3,BattlefieldRankModule,[new ResVo("ui/uiBattlefields.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50510,3,BattlefieldRankRewardModule,[new ResVo("ui/uiBattlefields.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50508,3,BattlefieldReportModule,[new ResVo("ui/uiBattlefieldScenes.uibaz"),new ResVo("ui/uiBattlefields.uibaz"),new ResVo("effect2d/battle/dgWinLogo.swf",14),new ResVo("effect2d/battle/lossLogo.swf",14)]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50509,3,BattlefieldFightResultModule,[new ResVo("ui/uiBattlefieldScenes.uibaz"),new ResVo("ui/uiBattlefieldScenes.uibaz"),new ResVo("effect2d/battle/dgWinLogo.swf",14),new ResVo("effect2d/battle/lossLogo.swf",14)]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50507,1,BattlefieldSceneModule,[new ResVo("ui/uiBattlefieldScenes.uibaz"),new ResVo("ui/uiBattlefields.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10210,4,TipMenuModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(41500,1,ShenYuanModule,[new ResVo("ui/uiShenYuan.uibaz"),new ResVo("ui/uiActRank.uibaz"),new ResVo("ui/uiRankReward.uibaz"),new ResVo("effect2d/shenyuan/secretBoxEff.swf",14)]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(41504,1,ShenYuanBattleModule,[new ResVo("ui/uiDungeonScene.uibaz"),new ResVo(UrlLib.skillConfigUrl(),10),new ResVo("ui/fightText.swf")]).set_loadingAutoAdd(false));
         ModuleMgr.ins.regModule(new ModuleConfigVo(41505,3,SYLuckRewardModule,[new ResVo("ui/uiLuckyReward.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(41502,3,ShenYuanHelpPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40540,1,TestSceneModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40500,1,MainCityModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40400,3,DungeonMapModule,[new ResVo("ui/uiChapter.uibaz",0,0,1)]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40401,3,TreasureBoxModule,[new ResVo("ui/uiChapter.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40404,3,EliteInvadeModule,[new ResVo("ui/uiChapter.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40406,3,EliteInvadeInfoPanel,[new ResVo("ui/uiChapter.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40407,3,DungeonInfoPanel,[new ResVo("ui/uiChapter.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40300,1,DungeonSceneModule,[new ResVo("ui/uiDungeonScene.uibaz"),new ResVo(UrlLib.skillConfigUrl(),10),new ResVo("ui/fightText.swf")]).set_loadingAutoAdd(false));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40200,1,FightSceneModule,[new ResVo("ui/uiDungeonScene.uibaz"),new ResVo(UrlLib.skillConfigUrl(),10),new ResVo("ui/fightText.swf")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(41400,1,ResourceDungeonModule,[new ResVo("ui/uiDungeonScene.uibaz"),new ResVo("ui/uiResourceDungeons.uibaz"),new ResVo(UrlLib.skillConfigUrl(),10),new ResVo("ui/fightText.swf")]).set_loadingAutoAdd(false));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13315,1,NewYear2016BossFightModule,[new ResVo("ui/uiDungeonScene.uibaz"),new ResVo("ui/uiResourceDungeons.uibaz"),new ResVo(UrlLib.skillConfigUrl(),10),new ResVo("ui/fightText.swf")]).set_loadingAutoAdd(false));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40405,1,EliteInvadeSceneModule,[new ResVo("ui/uiDungeonScene.uibaz"),new ResVo(UrlLib.skillConfigUrl(),10),new ResVo("ui/fightText.swf")]).set_loadingAutoAdd(false));
         ModuleMgr.ins.regModule(new ModuleConfigVo(41215,1,SubpalaceBossFightModule,[new ResVo("ui/uiDungeonScene.uibaz"),new ResVo(UrlLib.skillConfigUrl(),10),new ResVo("ui/fightText.swf")]).set_loadingAutoAdd(false));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30815,3,ReinforceTrainModule,[new ResVo("ui/uiReinforceTrain.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(90100,1,TestScene3DModule7,[new ResVo("ui/uiDungeonScene.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10600,3,FriendModule,[new ResVo("ui/uiFriend.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10602,3,FriendSearchOneModule,[new ResVo("ui/uiFriend.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10601,3,FriendRecommendModule,[new ResVo("ui/uiFriend.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10603,3,FriendApplyModule,[new ResVo("ui/uiFriend.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10621,3,FriendGiftModule,[new ResVo("ui/uiFriend.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10622,3,FriendLogModule,[new ResVo("ui/uiFriend.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10700,3,FmailMainModule,[new ResVo("ui/uiMail.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10701,3,ReadMailPanel,[new ResVo("ui/uiMail.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10702,3,WriteMailPanel,[new ResVo("ui/uiMail.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30100,3,RoleInfoModule,[new ResVo("ui/uiRoleInfo.uibaz"),new ResVo("ui/uiRoleTeam.uibaz")]));
         _loc1_ = new ModuleConfigVo(30103,3,RoleTupoSuccessModule,[new ResVo("ui/uiRoleInfo.uibaz")]);
         ModuleMgr.ins.regModule(new ModuleConfigVo(30103,3,RoleTupoSuccessModule,[new ResVo("ui/uiRoleInfo.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30111,3,RoleTupoGodhoodModule,[new ResVo("ui/uiRoleInfo.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30112,3,RoleTupoConfirmModule,[new ResVo("ui/uiRoleInfo.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30122,3,RoleAwakeEquipFullModule,[new ResVo("ui/uiRoleInfo.uibaz")]));
         _loc1_.useCoverKind = 4;
         ModuleMgr.ins.regModule(new ModuleConfigVo(30105,3,RoleShenjieTujianPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30107,3,RoleShenjieSuccessPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30500,3,EquipGrowModule,[new ResVo("ui/uiRoleInfo.uibaz"),new ResVo("ui/uiEquipGrow.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30300,3,HorseMainModule,[new ResVo("ui/uiHorse.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30330,3,HorseShengjieCplModule,[new ResVo("ui/uiHorse.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30400,3,MilitaryModule,[new ResVo("ui/uiMilitaryRankInfo.uibaz"),new ResVo("ui/uiPlayerTitle.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30200,3,FashionModule,[new ResVo("ui/uiFashion.uibaz"),new ResVo("ui/uiFashionUpgrade.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(31100,3,SkinModule,[new ResVo("ui/uiSkinMain.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(31110,3,SkinBookModule,[new ResVo("ui/uiSkin.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30617,3,TreasureFuwenKeyinCplModule,[new ResVo("ui/uiHorse.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(11000,3,BagModule,[]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(11040,3,EquipCompose,[]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(60550,3,ActivityExchange,[]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(11030,3,UseBatchView,[]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(11039,3,YIYEView,[]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30701,3,HeroShowModule,[new ResVo("ui/uiRoleInfo.uibaz"),new ResVo("ui/uiHeroShow.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(1000001,3,GuildHeroShardListModule,[]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(11500,3,FSignInModule,[new ResVo("ui/uiSignIn.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30810,3,RoleTeamModule,[new ResVo("ui/uiRoleTeam.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30811,3,EquipMasterPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30600,3,TreasureModule,[new ResVo("ui/uiTreasure.uibaz"),new ResVo("ui/uiTreasure2.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30601,3,SelectTreasurePanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30602,3,RuneComposePanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30604,3,RuneBatchCompsePanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30605,3,RuneBatchComposePreviewPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30606,3,RuneBatchComposeSuccessPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30113,3,PhaseUpTalentPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(11600,3,OtherRoleInfoModule,[new ResVo("ui/uiRoleTeam.uibaz"),new ResVo("ui/uiRoleInfo.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(11700,3,HCModule,[new ResVo("ui/uiHeroCompare.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(11701,3,HCSelectHeroPanel,[new ResVo("ui/uiHeroCompare.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(42000,1,TeamPKCModule,[new ResVo("ui/uiTeamPKCS.uibaz"),new ResVo("ui/uiTeams.uibaz"),new ResVo("ui/fightText.swf"),new ResVo("effect2d/battle/dgWinLogo.swf",14),new ResVo("effect2d/battle/lossLogo.swf",14)]));
         _loc1_ = new ModuleConfigVo(42005,3,TPKCChangeOrder,[]);
         ModuleMgr.ins.regModule(new ModuleConfigVo(42005,3,TPKCChangeOrder,[]));
         _loc1_.useCoverKind = 1;
         ModuleMgr.ins.regModule(new ModuleConfigVo(42006,3,TPKCRankModule,[new ResVo("ui/uiRankModule.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(42007,3,TPKCReportPanel,[new ResVo("ui/uiTeamPKCS.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(42004,3,TPKCInviteList,[new ResVo("ui/uiTeamPKCS.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(42010,3,TPKWinnerShowModule,[new ResVo("ui/uiWinnerShow.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(42011,3,TPKCGambleModule,[new ResVo("ui/uiTeamPKCS.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(42012,3,TPKCMyGamblePanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(42009,3,TPKCRankRewardModule,[]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(42014,3,TPKIntroPanel,[new ResVo("ui/uiPkIntro.uibaz"),new ResVo("ui/uiTPKIntro.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10110,4,FloadMsgModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10112,4,EventNoticeModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10113,4,MsgTopCenterModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(96400,4,NewerAlertModule,[new ResVo("ui/uiNewerAlert.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(96500,4,QuickUseModule,[new ResVo("ui/uiQuickUseModules.uibaz")]));
         _loc1_ = new ModuleConfigVo(96701,2,NewerFunctionOpen,[new ResVo("ui/uiQuickUseModules.uibaz")]);
         ModuleMgr.ins.regModule(new ModuleConfigVo(96701,2,NewerFunctionOpen,[new ResVo("ui/uiQuickUseModules.uibaz")]));
         _loc1_ = new ModuleConfigVo(10100,3,SimpleAlert);
         ModuleMgr.ins.regModule(new ModuleConfigVo(10100,3,SimpleAlert));
         _loc1_.useCoverKind = 1;
         _loc1_ = new ModuleConfigVo(10102,4,SimpleAlert);
         ModuleMgr.ins.regModule(new ModuleConfigVo(10102,4,SimpleAlert));
         _loc1_.useCoverKind = 1;
         ModuleMgr.ins.regModule(new ModuleConfigVo(12000,3,PwdModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40100,3,PositionModule,[new ResVo("ui/uiPosition.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(11800,3,RankModule,[new ResVo("ui/uiRankModule.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50247,3,PKCrossRankModule,[new ResVo("ui/uiRankModule.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50249,3,WinnerShowModule,[new ResVo("ui/uiWinnerShow.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(60310,3,MysteryShopModule,[new ResVo("ui/uiShop.uibaz"),new ResVo("modules/shops/img_mysteryPanelBg.png")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(60320,3,ShopBuyModule,[new ResVo("ui/uiShop.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(60300,3,ShopModule,[new ResVo("ui/uiShop.uibaz"),new ResVo("modules/shops/img_avatar.png"),new ResVo("modules/shops/img_shopPanelBg.png")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(60500,3,ActivityModule,[new ResVo("ui/uiActivity.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(14000,3,RecommendHeroModule,[new ResVo("ui/uiRecommendHero.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30106,3,SkillChangeModule,[new ResVo("ui/uiSkillChange.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(90400,4,LoadingModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(96100,4,NewerGuideModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13000,3,DailyTaskModule,[new ResVo("ui/uiDailyTask.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(12002,3,HeroChooseModule,[new ResVo("ui/uiHeroChoose.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(11300,3,RecycleModule,[new ResVo("ui/uiRecycle.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(11301,3,RecSelectHeroPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(11302,3,RecSelectEquiipPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(11304,3,RecycleConfirmPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(11303,3,RecSelectRebornHeroPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(11305,3,RecSelectRebornTreasurePanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(11308,3,RecSelectRecTreasurePanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(11310,3,HeroMirrorSelectHeroPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(11309,3,RecSelectRebornPetPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40700,3,GuildModule,[new ResVo("ui/uiGuildModule.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40702,3,GuildAppointPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40701,3,GuildVerifyPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40703,3,GuildDonatePanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40704,3,GuildUpgradePanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40705,3,GuildChangeNoticePanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40706,3,CreateGuildPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40707,3,GuildLogPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40708,3,GuildFlagPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40709,3,GuildDetialInfoPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40710,3,SetAuthrorityPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40711,3,GuildListPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40713,3,GuildInviteFriendPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40750,3,GuildTechModule,[new ResVo("ui/uiGuildTechs.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40751,3,GuildTechResearchModule,[new ResVo("ui/uiGuildTechs.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40720,3,GuildDungeonModule,[new ResVo("ui/uiGuildDungeon.uibaz"),new ResVo("ui/uiChapter.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40721,1,GuildDungeonSceneModule,[new ResVo("ui/uiDungeonScene.uibaz"),new ResVo(UrlLib.skillConfigUrl(),10),new ResVo("ui/fightText.swf")]).set_loadingAutoAdd(false));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40725,1,GuildDungeonYukouSceneModule,[new ResVo("ui/uiDungeonScene.uibaz"),new ResVo(UrlLib.skillConfigUrl(),10),new ResVo("ui/fightText.swf")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40722,3,GuildDungeonTargetModule,[new ResVo("ui/uiGuildDungeon.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40723,3,GuildDungeonTreasureModule,[new ResVo("ui/uiGuildDungeon.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40726,3,GuildDungeonVideoPanel,[new ResVo("ui/uiGuildDungeon.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40740,1,FamilyBossModule,[new ResVo("ui/uiFamilyBosses.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40741,1,FamilyBossFightModule,[new ResVo("ui/uiDungeonScene.uibaz"),new ResVo(UrlLib.skillConfigUrl(),10),new ResVo("ui/fightText.swf")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40742,3,FamilyBossSetTimeModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40743,3,FamilyBossDmgRewardModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40744,3,FamilyBossHornorRankModule,[new ResVo("ui/uiFamilyBossHornor.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(41600,3,NpcFuncListModule,[new ResVo("ui/uiNpcFuncLists.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50900,3,FunnyEventModule,[new ResVo("ui/uiFunnyEvents.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50246,3,PKCrossCheerModule,[new ResVo("ui/uiPKCrossSer.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50248,3,PKCrossReportModule,[new ResVo("ui/uiFunnyEvents.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50600,1,PKCrossModule,[new ResVo("ui/uiPKCrossSer.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40760,1,GPKCrossModule,[new ResVo("ui/uiGuildPKCrossSer.uibaz"),new ResVo("effect2d/battle/dgWinLogo.swf",14),new ResVo("effect2d/battle/lossLogo.swf",14)]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40761,3,GPKStartPanel,[new ResVo("ui/uiGuildPKCrossSer.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40767,3,GPKQuestPanel,[new ResVo("ui/uiGuildPKCrossSer.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40762,3,GPKLotteryPanel,[new ResVo("ui/uiGuildPKCrossSer.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40763,3,GPKSkillPanel,[new ResVo("ui/uiGuildPKCrossSer.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40765,3,GPKReportModule,[new ResVo("ui/uiFunnyEvents.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40764,3,GPKRankModule,[new ResVo("ui/uiRankModule.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40769,3,GPKSkillRankPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40770,3,GPKWinnerShowModule,[new ResVo("ui/uiWinnerShow.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40771,3,GPKRankReward,[new ResVo("ui/uiGuildPKCrossSer.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40772,3,GPKChallReward,[new ResVo("ui/uiGuildPKCrossSer.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(40773,3,GPKIntroPanel,[new ResVo("ui/uiGuildPKCrossSer.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50200,1,ArenaModule,[new ResVo("ui/uiArenas.uibaz"),new ResVo("ui/uiRankReward.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50242,3,ArenaRewardModule,[new ResVo("ui/uiArenas.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50231,3,ArenaRankModule,[new ResVo("ui/uiArenas.uibaz"),new ResVo("ui/uiActRank.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50241,3,ArenaScoreModule,[new ResVo("ui/uiArenas.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50230,3,ArenaBattleResultModule,[new ResVo("ui/uiArenas.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50400,1,ChampionShipModule,[new ResVo("ui/uiChampionship.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50401,3,ChampionGamblePanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50402,3,ChampionRewardPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50403,3,ChampionGambleRecordPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50404,3,ChampionshipCompeteRecordPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10623,3,TeamListModule,[new ResVo("ui/uiTeams.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10624,3,TeamDetailModule,[new ResVo("ui/uiTeams.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10625,3,TeamApplyList,[new ResVo("ui/uiTeams.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(41210,1,TeamGuajiScene,[new ResVo("ui/uiTeamGuajis.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(41211,3,GuajiChangeChallengeModule,[new ResVo("ui/uiTeamGuajis.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(41212,2,guajiBag,[new ResVo("ui/uiTeamGuajis.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(41216,3,TeamInviteFriendModule,[new ResVo("ui/uiTeamGuajis.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(41217,3,TreasurePieceBagModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(41218,3,TreasureComposeModule,[new ResVo("ui/uiTreasureCompose.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(41219,3,RobTreasurePieceModule,[new ResVo("ui/uiTeamGuajiPvP.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(41221,3,TeamGuajiRankModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(41223,1,TeamGuajiPvPFightModule,[new ResVo("ui/uiDungeonScene.uibaz"),new ResVo(UrlLib.skillConfigUrl(),10),new ResVo("ui/fightText.swf")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(41225,2,TeamGuajiMiniPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(10630,2,NoticeModule));
         _loc1_ = new ModuleConfigVo(10150,3,RoleLvlUpModule,[new ResVo("ui/uiLvlUpModule.uibaz")]);
         ModuleMgr.ins.regModule(new ModuleConfigVo(10150,3,RoleLvlUpModule,[new ResVo("ui/uiLvlUpModule.uibaz")]));
         _loc1_.useCoverKind = 1;
         ModuleMgr.ins.regModule(new ModuleConfigVo(96200,2,SeePlayerModule,[new ResVo("ui/uiSeePlayer.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(11200,3,MallModule,[new ResVo("ui/uiMall.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(11201,3,MallBuyConfirmModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(11202,2,MallAlertModule,[new ResVo("ui/uiMallAlert.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(96300,3,GetItemsDisplayModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(96030,3,ExchangeModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30610,3,AuctionShopModule,[new ResVo("ui/uiAuctionShop.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30611,3,AuctionSellItemPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30612,3,AuctionBuyItemPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(60763,3,AbilityRankModule,[new ResVo("ui/uiAbilityRank.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30121,3,HeroAwakenRoadModule,[new ResVo("ui/uiHeroAwakenRoad.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(30199,1,HeroAwakenRoadFightModule,[new ResVo("ui/uiDungeonScene.uibaz"),new ResVo(UrlLib.skillConfigUrl(),10),new ResVo("ui/fightText.swf")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(88001,3,FBInviteViewModule,[new ResVo("ui/uiFacebook.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(88002,3,FBShareModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(89001,3,ResRecoveryModule,[new ResVo("ui/uiResRecovery.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(90001,3,FBFansPageModule,[new ResVo("ui/uiFBFansPage.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(41700,1,WorldBossModule,[new ResVo("ui/uiWorldBoss.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(41701,3,WorldBossRankModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(60560,3,GrouponModule,[new ResVo("ui/uiGroupon.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(60561,3,GrouponBuyItemConfirmModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13400,3,CharmStarModule,[new ResVo("ui/uiCharmStar.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13405,3,UseGiftView,[new ResVo("ui/uiSendChoco.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13406,3,CharmStarUseCocoConfirmModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13407,3,CharmStarBuyConfirmModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(60800,3,DialModule,[new ResVo("ui/uiDialModules.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(60810,3,DialModule,[new ResVo("ui/uiFunnyCommon.uibaz"),new ResVo("ui/uiDialModules.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(900400,3,AngelFundModule,[new ResVo("ui/uiAngelFund.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13350,3,LuckTreeModule,[new ResVo("ui/uiLuckTree.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13355,3,Day51Module,[new ResVo("ui/uiFunnyCommon.uibaz"),new ResVo("ui/uiDay51.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13360,3,Day51HelpModule,[]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(60901,3,GoldenDiamondChangeModule,[new ResVo("ui/uibaz/uiGoldenShop.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(31200,3,FashionAccModule,[new ResVo("ui/uiFashionUpgrade.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(31210,3,FashionAccSelectModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(1410065407,3,MysteryShopHeroShardListModule,[new ResVo("ui/uiHeroShow.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(31221,3,FashionAccSkillWindow,[new ResVo("ui/uiSkillChange.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(900500,3,Foolday2016Module,[new ResVo("ui/uiFoolday.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13110,3,Foolday2016Module,[new ResVo("ui/uiFoolday.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(32000,3,PetModule,[new ResVo("ui/uiPet.uibaz"),new ResVo("ui/uiRoleInfo.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(32031,3,PetStarPreViewPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(32033,3,PetSelectModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(32032,3,PetSkinModule));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50700,1,SecretExploreModule,[new ResVo("ui/uiSecretExplore.uibaz"),new ResVo("effect2d/secretExplore/line.swf",14)]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50703,3,SEHelpPanel));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50704,3,SEAssistRank));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50705,3,SEScoreModule,[new ResVo("ui/uiArenas.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50701,1,SEBattleModule,[new ResVo("ui/uiDungeonScene.uibaz"),new ResVo(UrlLib.skillConfigUrl(),10),new ResVo("ui/fightText.swf")]).set_loadingAutoAdd(false));
         ModuleMgr.ins.regModule(new ModuleConfigVo(9900004,3,OlmpicSelCountryModule));
         _loc1_ = new ModuleConfigVo(50520,3,PeakSportsModule,[new ResVo("ui/uiPeakSports.uibaz")]);
         ModuleMgr.ins.regModule(new ModuleConfigVo(50520,3,PeakSportsModule,[new ResVo("ui/uiPeakSports.uibaz")]));
         _loc1_.useCoverKind = 1;
         ModuleMgr.ins.regModule(new ModuleConfigVo(50532,3,PeakSportsRewardModule,[new ResVo("ui/uiPeakSports.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50526,3,PeakSportsIntroduceModule,[new ResVo("ui/uiPeakSports.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50528,3,PeakSportsReportModule,[new ResVo("ui/uiPeakSportsScenes.uibaz"),new ResVo("ui/uiPeakSports.uibaz"),new ResVo("effect2d/battle/dgWinLogo.swf",14),new ResVo("effect2d/battle/lossLogo.swf",14)]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50527,1,PeakSportsSceneModule,[new ResVo("ui/uiPeakSportsScenes.uibaz"),new ResVo("ui/uiPeakSports.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(50529,3,PeakSportsFightResultModule,[new ResVo("ui/uiPeakSports.uibaz"),new ResVo("effect2d/battle/dgWinLogo.swf",14),new ResVo("effect2d/battle/lossLogo.swf",14)]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13386,3,TowerModule,[new ResVo("ui/uiFunnyCommon.uibaz"),new ResVo("ui/uiTower.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(900600,3,QuestionModule,[new ResVo("ui/uiQuestion.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13376,3,DragonBoatModule,[new ResVo("ui/uiFunnyCommon.uibaz"),new ResVo("ui/uiDragonBoat.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13382,3,DragonBoatHelpModule,[new ResVo("ui/uiFunnyCommon.uibaz"),new ResVo("ui/uiDragonBoat.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13383,3,DragonBoatFunnyMakeConfirm,[new ResVo("ui/uiFunnyCommon.uibaz"),new ResVo("ui/uiDragonBoat.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13384,3,DragonBoatDonateConfirm,[new ResVo("ui/uiFunnyCommon.uibaz"),new ResVo("ui/uiDragonBoat.uibaz")]));
         ModuleMgr.ins.regModule(new ModuleConfigVo(13385,3,DragonBoatDonateRequestPanel,[new ResVo("ui/uiFunnyCommon.uibaz"),new ResVo("ui/uiDragonBoat.uibaz")]));
         if(ClientConfig.firstBattle == 0)
         {
            UIMgr.stage.addEventListener("resize",onResize);
            var _loc2_:* = new MainBlackRim();
            UIMgr.rootRim = _loc2_;
            UIMgr.root.parent.addChild(_loc2_);
         }
         onResize(null);
         this.onComplete();
      }
      
      private function onResize(param1:Event) : void
      {
         UIMgr.ins.resize(param1);
      }
   }
}
