package nslm2.nets.sockets
{
   import com.mz.core.utils.DictHash;
   import com.netease.protobuf.Message;
   import proto.GetPlayerOnlineDataRes;
   import proto.FashionListRes;
   import proto.XunleiJinzuanInfoNotify;
   import proto.FunctionActionNotify;
   import proto.SaddleHorseNotify;
   import proto.BattleSvrCloseNotify;
   import proto.TestRes;
   import proto.OnlineSceneNotify;
   import proto.TeamListRes;
   import proto.TeamCreateRes;
   import proto.TeamCreateNotify;
   import proto.TeamInvitedNotify;
   import proto.TeamEnterNotify;
   import proto.TeamMemInfoNotify;
   import proto.TeamGetInfoRes;
   import proto.TeamMemberSynNotify;
   import proto.TeamInfoNotify;
   import proto.TeamCountChangeNotify;
   import proto.TeamReadyNotify;
   import proto.TeamKickNotify;
   import proto.TeamPwdNotify;
   import proto.TeamChangeheroNotify;
   import proto.TeamStartNotify;
   import proto.TeamBuzhenNotify;
   import proto.TeamLeaveNotify;
   import proto.TeamReplyRes;
   import proto.TeamReplyNotify;
   import proto.TeamDismissNotify;
   import proto.TeamStopNotify;
   import proto.TeamChangeNameNotify;
   import proto.BattleTestRes;
   import proto.BattleTestStartNotify;
   import proto.BattleActionNotify;
   import proto.SystemSettingsNotify;
   import proto.HeartBeat;
   import proto.ProtocolStatusRes;
   import proto.RandomNameRes;
   import proto.PlayerLevelVipInfoNotify;
   import proto.ClientLoadFinishRes;
   import proto.WearChangeNotify;
   import proto.PlayerInfoNotify;
   import proto.PlayerDataNotify;
   import proto.EnterScenePlayerNotify;
   import proto.EnterSceneOtherPlayerNotify;
   import proto.LeaveSceneNotify;
   import proto.ShowLineStateRes;
   import proto.ShowLineNumberRes;
   import proto.StageFightStartRes;
   import proto.StagePhaseCheckRes;
   import proto.StageFightEndRes;
   import proto.EliteInvadeFightStartRes;
   import proto.EliteInvadeFightEndRes;
   import proto.GetStageInfosRes;
   import proto.EliteInvadeNotify;
   import proto.GetChapterInfosRes;
   import proto.StageSaoDangRes;
   import proto.TestDropGroupRes;
   import proto.NormalBagRes;
   import proto.EquipBagRes;
   import proto.ShowItemRes;
   import proto.PanelViewRes;
   import proto.ExpHeroesRes;
   import proto.HeroAddExpRes;
   import proto.BaseProp;
   import proto.HeroShengjieRes;
   import proto.HeroShengjieRecordRes;
   import proto.HeroInfoNotify;
   import proto.HeroAllInfoNotify;
   import proto.BuZhenInfo;
   import proto.BuZhenViewRes;
   import proto.BuZhenListRes;
   import proto.BuZhenSupportRes;
   import proto.LuckTreeWorldExpNotify;
   import proto.LuckTreeGetRewardRes;
   import proto.LuckTreeDajiangNotify;
   import proto.LuckTreeBuyRes;
   import proto.LuckTreeCheerRes;
   import proto.LuckTreeInfoRes;
   import proto.ZhuanPanDajiangRes;
   import proto.ZhuanPanRankDataRes;
   import proto.ZhuanPanBuyRes;
   import proto.ZhuanPanCommonRes;
   import proto.ZhuanPanSuperRes;
   import proto.ZhuanPanInfoRes;
   import proto.XunleiJinzuanGetRewardRes;
   import proto.OpenChallengeNotify;
   import proto.OpenChallengeInfoRes;
   import proto.OpenChallengeGetRewardRes;
   import proto.ShunWangGetRewardRes;
   import proto.JueRoadInfoRes;
   import proto.JueRoadFightStartRes;
   import proto.JueRoadSaoDangRes;
   import proto.JueRoadFightEndRes;
   import proto.JueRoadGetRewardRes;
   import proto.JueRoadRecordRes;
   import proto.ShenGridInfoRes;
   import proto.ShenGridClickRes;
   import proto.ShenGridChooseRes;
   import proto.WeixinGetRewardNotify;
   import proto.WeixinGetRewardRes;
   import proto.MobileCheckGetCodeRes;
   import proto.MobileCheckRes;
   import proto.MobileCheckGetRewardRes;
   import proto.DuowanNewerCardRes;
   import proto.SougouGetRewardRes;
   import proto.SougouInputGetRewardRes;
   import proto.PrivilegeWeiShiCheckRes;
   import proto.OpenFundInfoRes;
   import proto.OpenFundBuyFundRes;
   import proto.OpenFundGetFundRewardRes;
   import proto.OpenFundGetWelfareRes;
   import proto.OpenFundWelfareNotify;
   import proto.SuperSaleResetNotify;
   import proto.SuperSaleRechargeExtraRewardNotify;
   import proto.SuperSaleInfoRes;
   import proto.SuperSaleGetRewardRes;
   import proto.SuperSaleBuyItemRes;
   import proto.SuperSaleAllCountNotify;
   import proto.ActivateCodeRes;
   import proto.HeroPracticeInfoRes;
   import proto.HeroPracticeEnterNodeRes;
   import proto.HeroPracticeFightStartRes;
   import proto.HeroPracticeFightEndRes;
   import proto.HeroPracticeSaoDangRes;
   import proto.HeroPracticeTimesNotify;
   import proto.HeroPracticeResetNotify;
   import proto.PlayerMoveNotify;
   import proto.PlayerMilitaryrankUpgradeRes;
   import proto.PlayerMilitaryrankInfoRes;
   import proto.PlayerFriendApplyRes;
   import proto.PlayerFriendApplyNotify;
   import proto.PlayerDeleteFriendRes;
   import proto.PlayerDeleteFriendNotify;
   import proto.PlayerFriendSearchRes;
   import proto.PlayerFriendRecommendRes;
   import proto.PlayerFriendNextRes;
   import proto.PlayerFriendsInfoRes;
   import proto.PlayerSeeFriendInfoRes;
   import proto.PlayerApplyAgreeRes;
   import proto.PlayerApplyAgreeNotify;
   import proto.PlayerFriendChatNotify;
   import proto.PlayerApplyRefuseNotify;
   import proto.PlayerApplyRefusePiLiangRes;
   import proto.PlayerApplyPiLiangRes;
   import proto.PlayerApplyAgreePiLiangRes;
   import proto.PlayerOnlineNotify;
   import proto.PlayerOfflineNotify;
   import proto.PlayerAddToHeiMingDanRes;
   import proto.PlayerRemoveHeiMingDanRes;
   import proto.FriendSignatureRes;
   import proto.FriendSignatureNotify;
   import proto.FriendDonateStaminaRes;
   import proto.FriendDonateStaminaAllRes;
   import proto.FriendStaminaGetRes;
   import proto.FriendStaminaGetAllRes;
   import proto.FriendDonateStaminaNotify;
   import proto.FriendTrendsRes;
   import proto.FriendTrendNotify;
   import proto.FriendCongratulateRes;
   import proto.FriendCongratulateAllRes;
   import proto.FriendCongratulateNotify;
   import proto.FriendStaminaInfoRes;
   import proto.FriendDailyInfoClearNotify;
   import proto.PlayerActivateSaddleHorseRes;
   import proto.PlayerUseSaddleHorseRes;
   import proto.PlayerUnuseSaddleHorseRes;
   import proto.PlayerChangeSaddleHorseRes;
   import proto.PlayerChangeGloryRes;
   import proto.PlayerGetSaddleHorsesRes;
   import proto.PlayerGetGloriesRes;
   import proto.PlayerGetCurrentSaddleHorseRes;
   import proto.PlayerGetCurrentGloryRes;
   import proto.PlayerSaddleHorseUpgradeRes;
   import proto.PlayerBossZhaoHuanFreeTimeRes;
   import proto.PlayerBossZhaoHuanRes;
   import proto.PlayerSaddleHorseYanJiuRes;
   import proto.PlayerSaddleHorseYanJiuOneKeyRes;
   import proto.PlayerResStageFightEndRes;
   import proto.WorldBossStartEventNotify;
   import proto.WorldBossNextWaveNotify;
   import proto.WorldBossMemberReliveNotify;
   import proto.WorldBossInfoRes;
   import proto.WorldBossQuickFightStartRes;
   import proto.WorldBossTopRankNotify;
   import proto.WorldBossInfoNotify;
   import proto.WorldBossMemberDeadNotify;
   import proto.WorldBossHurtInfoRes;
   import proto.WorldBossHurtRewardRes;
   import proto.WorldBossJoinFightStartRes;
   import proto.WorldBossModelSetRes;
   import proto.FamilyBossSupperRankRes;
   import proto.FamilyBossQuickFightStartRes;
   import proto.FamilyBossHurtRewardRes;
   import proto.FamilyBossInfoNotify;
   import proto.FamilyBossNextWaveNotify;
   import proto.FamilyBossTopRankNotify;
   import proto.FamilyBossStartEventNotify;
   import proto.FamilyBossNextStartTimeNotify;
   import proto.FamilyBossInfoRes;
   import proto.FamilyBossSetNextStartTimeRes;
   import proto.FamilyBossBuyGuliRes;
   import proto.FamilyBossHurtInfoRes;
   import proto.FamilyBossModelSetRes;
   import proto.FamilyBossReliveRes;
   import proto.FamilyBossMemberReliveNotify;
   import proto.FamilyBossMemberDeadNotify;
   import proto.FamilyBossJoinFightStartRes;
   import proto.FamilyBossJoinFightEndRes;
   import proto.FamilyBossBossReliveNotify;
   import proto.FamilyBossBossBuffNotify;
   import proto.FamilyStageChapterSelectRes;
   import proto.FamilyStageGetRewardRes;
   import proto.FamilyStageChapterSelectNotify;
   import proto.FamilyStageGetRewardNotify;
   import proto.FamilyStageRewardInfoRes;
   import proto.FamilyStageRecordRes;
   import proto.FamilyStageEnterChapterRes;
   import proto.FamilyStageFightStartRes;
   import proto.FamilyStageFightEndRes;
   import proto.FamilyStageYuKouStartRes;
   import proto.FamilyStageYuKouEndRes;
   import proto.FamilyStageYuKouSaoDangRes;
   import proto.FamilyStageHurtRankRes;
   import proto.FamilyStageHpsNotify;
   import proto.FamilyStageResetNotify;
   import proto.FamilyStageFightStartNotify;
   import proto.FamilyStageFightEndNotify;
   import proto.FamilyStageNodeRankRes;
   import proto.FamilyStageBuyTimesRes;
   import proto.FamilyStageTimesNotify;
   import proto.FamilyTechInfoRes;
   import proto.FamilyTechResearchRes;
   import proto.FamilyTechStudyRes;
   import proto.FamilyTechResearchNotify;
   import proto.EquipPanelViewRes;
   import proto.EquipStrengthRes;
   import proto.EquipJinglianRes;
   import proto.EquipAddStarRes;
   import proto.PublicTalkNotify;
   import proto.EventNotify;
   import proto.PublicTalkMultiNotify;
   import proto.PrivateTalkNotify;
   import proto.PTChatPlayerInfoRes;
   import proto.FamilyInfoRes;
   import proto.FamilyApplyRes;
   import proto.FamilyOtherRes;
   import proto.FamilyQuitRes;
   import proto.FamilyMemberRes;
   import proto.FamilyApplyListRes;
   import proto.FamilyListRes;
   import proto.FamilyDonateRes;
   import proto.FamilyChangeNoticeRes;
   import proto.FamilyLogRes;
   import proto.FamilyApplyNotify;
   import proto.FamilyGetAuthorityRes;
   import proto.FamilyMemberInfoRes;
   import proto.FamilyAuthorityNotify;
   import proto.FamilyDonateScoreRes;
   import proto.DelMailNotify;
   import proto.GetMailListRes;
   import proto.ReadMailRes;
   import proto.GetMailRewardRes;
   import proto.DelMailRes;
   import proto.MailNotify;
   import proto.NewGroupMailNotify;
   import proto.BaoWuBagRes;
   import proto.BaoWuStrengthRes;
   import proto.BaoWuKeyinRes;
   import proto.BaoWuFumoRes;
   import proto.BaoWuFumoOpenRes;
   import proto.BaoWuMoshiAllRes;
   import proto.MoShiCombineRecordRes;
   import proto.BaoWuFumoAllRes;
   import proto.BaoWuGoldCombineRes;
   import proto.BaoWuPurifyRes;
   import proto.BaoWuRemouldRes;
   import proto.GetShenYuanInfoRes;
   import proto.ShenYuanReceiveBoxRes;
   import proto.ShenYuanGetMysteriBoxRes;
   import proto.ShenYuanTongGuanRes;
   import proto.ShenYuanRequestFriendRes;
   import proto.FightShenYuanStartRes;
   import proto.FightShenYuanEndRes;
   import proto.ShenYuanBuyBuffRes;
   import proto.ShenYuanPaiMingRes;
   import proto.ShenYuanRankRewardRes;
   import proto.ShenYuanGetLuckyBoxRes;
   import proto.LotteryInfoRes;
   import proto.LotteryRandRes;
   import proto.LotterySuperRes;
   import proto.LotteryGetRewardRes;
   import proto.GuajiSaoDangRes;
   import proto.GuajiPvpBeStealNotify;
   import proto.GuajiInfoRes;
   import proto.GuajiInfoNotify;
   import proto.GuajiBossFightStartRes;
   import proto.GuajiBossFightEndRes;
   import proto.GuajiGetBagInfoRes;
   import proto.GuajiExtraRewardNotify;
   import proto.GuajiLogRes;
   import proto.GuajiSwitchNotify;
   import proto.GuajiFightStNotify;
   import proto.GuajiRewardDispNotify;
   import proto.GuajiChangePvperRes;
   import proto.GuajiPvpFightStartRes;
   import proto.GuajiPvpAutoFightRes;
   import proto.GuajiPvpFightEndRes;
   import proto.GuajiPvpTodayRankRes;
   import proto.GuajiPvpYestodayRankRes;
   import proto.CrossSceneWatchRes;
   import proto.CrossSceneEnterNotify;
   import proto.CrossSceneLeaveNotify;
   import proto.GuajiSomeDataNotify;
   import proto.BtlAddBuffNotify;
   import proto.BtlDelBuffNotify;
   import proto.BtlSkillNotify;
   import proto.BtlPlayerDeadNotify;
   import proto.BtlPlayerReviveNotify;
   import proto.BtlNpcHpNotify;
   import proto.StageBtlGuideRes;
   import proto.ClothesSkillBagRes;
   import proto.ClothesBagRes;
   import proto.ClothesActiveRes;
   import proto.GetYunBiaoStateRes;
   import proto.RefreshYunBiaoShipQualityRes;
   import proto.GetYunBiaoFlyInfoRes;
   import proto.ShowYunBiaoDaJieInfoRes;
   import proto.YunBiaoDaJieRes;
   import proto.ShopBuyRes;
   import proto.ShopRefreshRes;
   import proto.ShopListRes;
   import proto.MallListRes;
   import proto.MallBuyRes;
   import proto.MallNotify;
   import proto.TaskGetCurInfoRes;
   import proto.TaskInfoNotify;
   import proto.ActivityGetInfosRes;
   import proto.ActivityRewardNotify;
   import proto.StaticActivitysRes;
   import proto.ActivityHotUpdateNotify;
   import proto.ViewOtherPlayerRes;
   import proto.ArenaInfoRes;
   import proto.ArenaReportInfoRes;
   import proto.ArenaChallengeRes;
   import proto.ArenaMultiChallengeRes;
   import proto.ArenaClearCdDiamondRes;
   import proto.ArenaBuyTimesRes;
   import proto.ArenaChangeEnemyRes;
   import proto.ArenaGetRankRewardRes;
   import proto.ArenaGetRankListRes;
   import proto.ArenaReportNotify;
   import proto.RecycleHeroDecomposeRes;
   import proto.RecycleEquipDecomposeRes;
   import proto.RecycleBaowuDecomposeRes;
   import proto.RecyclePetDecomposeRes;
   import proto.GetTimesBuyRes;
   import proto.GetSwapActionsRes;
   import proto.AbilityRankRes;
   import proto.LevelRankRes;
   import proto.FamilyRankRes;
   import proto.AreaRankRes;
   import proto.StageStarRankRes;
   import proto.RankSearchNameRes;
   import proto.SystemTimeNotify;
   import proto.CompeteInfoRes;
   import proto.CompeteGroupStageInfoRes;
   import proto.CompeteStatusTimeNotify;
   import proto.CompetePlayerDisplayRes;
   import proto.CompeteStageInfoRes;
   import proto.CompeteGambleInfoRes;
   import proto.CompeteGambleRewardRes;
   import proto.CompetePlayerRankInfoRes;
   import proto.CompeteOpenTimeRes;
   import proto.FunctionOpenTimeNotify;
   import proto.FunctionTimesNotify;
   import proto.GetSignInInfoRes;
   import proto.CanSignInRes;
   import proto.SignInRes;
   import proto.CanGetSignInExtraRes;
   import proto.SignInExtraRes;
   import proto.SevenDayInfoRes;
   import proto.FourteenInfoRes;
   import proto.SevenDayTimeStampRes;
   import proto.SevenDayShopSellOutNotify;
   import proto.SevenDayAvaiNumRes;
   import proto.BgInfoRes;
   import proto.BgTeamInfoRes;
   import proto.BgTeamNewMemNotify;
   import proto.BgTeamMemInfoNotify;
   import proto.BgRegNotify;
   import proto.BgLeaveNotify;
   import proto.BgBtlLeaveNotify;
   import proto.BgCheckRes;
   import proto.BgTeamDismissNotify;
   import proto.BgFriendsListRes;
   import proto.BgFamilyMemberListRes;
   import proto.BgFightNotify;
   import proto.BgFightNpcRes;
   import proto.BgFightNpcNotify;
   import proto.BgGatherNotify;
   import proto.BgGatherStatusNotify;
   import proto.BgResStatusNotify;
   import proto.BgStageGetReportRes;
   import proto.CrossSceneMoveNotify;
   import proto.BgStageEnterNotify;
   import proto.BgStageNewEnterNotify;
   import proto.BgCryStageInfoNotify;
   import proto.BgFireStageInfoNotify;
   import proto.BgStageEndNotify;
   import proto.BgDeadNotify;
   import proto.BgRebornNotify;
   import proto.BgPlayerStatusNotify;
   import proto.BgSceneMoveNotify;
   import proto.BgStageLeaveNotify;
   import proto.BgGetTitleRewardInfoRes;
   import proto.BgGetRankInfoRes;
   import proto.BgStartNotify;
   import proto.BgPlaceFlagNotify;
   import proto.CardInfoNotify;
   import proto.BkInfoRes;
   import proto.BkRegNotify;
   import proto.BkLeaveNotify;
   import proto.BkBtlLeaveNotify;
   import proto.BkCheckRes;
   import proto.BkSpecialCommandRes;
   import proto.BkSpecialCommandNotify;
   import proto.BkFightNotify;
   import proto.BkResStatusNotify;
   import proto.BkStageGetReportRes;
   import proto.BkStageEnterNotify;
   import proto.BkStageNewEnterNotify;
   import proto.BkGameStageInfoNotify;
   import proto.BkGameStepNotify;
   import proto.BkStageEndNotify;
   import proto.BkDeadNotify;
   import proto.BkRebornNotify;
   import proto.BkPlayerStatusNotify;
   import proto.BkSceneMoveNotify;
   import proto.BkStageLeaveNotify;
   import proto.BkStartNotify;
   import proto.GetVipInfoRes;
   import proto.GetVipRewardInfoRes;
   import proto.GetChargeInfoRes;
   import proto.VipReceiveChargeRewardRes;
   import proto.VipGetFirstChargeRes;
   import proto.VipMonthCardRes;
   import proto.VipGetFirstChargeRewardRes;
   import proto.CwPlayerInfoRes;
   import proto.CwCandidateListRes;
   import proto.CwShowGeneralRes;
   import proto.CwRandCampRes;
   import proto.CwCampListRes;
   import proto.CwCampDetailInfoRes;
   import proto.CwShowMarshalRes;
   import proto.GetAuctionListRes;
   import proto.AuctionSellItemRes;
   import proto.AuctionUnsellItemRes;
   import proto.AuctionBuyItemRes;
   import proto.AuctionMyListStatNotify;
   import proto.AuctionMyOrderRes;
   import proto.AuctionMySellsRes;
   import proto.BaoWuStatNotify;
   import proto.QqAddgoodsRes;
   import proto.QqGetTokenRes;
   import proto.QqGiftInfoRes;
   import proto.WeiDuanGetRewardRes;
   import proto.CrossArenaInfoRes;
   import proto.CrossArenaUpdateFinalEnemyRes;
   import proto.CrossArenaFightRes;
   import proto.CrossArenaChangeEnemyRes;
   import proto.CrossArenaRankInfoRes;
   import proto.CrossArenaSomeDataNotify;
   import proto.CrossArenaCheerRes;
   import proto.CrossArenaCheerInfoRes;
   import proto.CrossArenaHonorHallRes;
   import proto.CrossArenaFinalFightRes;
   import proto.CrossArenaGetReportRes;
   import proto.CrossArenaDistCheerRes;
   import proto.ActiveTitleRes;
   import proto.TitleChangeNotify;
   import proto.TitlePanelRes;
   import proto.WearTitleRes;
   import proto.FourteenDayNotify;
   import proto.FourteenDayShopBuyTimesRes;
   import proto.ValentineShopInfoRes;
   import proto.WhiteValentineShopInfoRes;
   import proto.LanternShopInfoRes;
   import proto.CharmRankStunnerRes;
   import proto.CharmRankReceiveMessageRes;
   import proto.CharmRankShopInfoRes;
   import proto.CharmRankShopDetailRes;
   import proto.CharmRankRankDetailRes;
   import proto.WhiteValentineStunnerRes;
   import proto.WhiteValentineReceiveMessageRes;
   import proto.GoddessVotePanelRes;
   import proto.GoddessVoteRes;
   import proto.GoddessScorePanelRes;
   import proto.GoddessShowPanelRes;
   import proto.SpringLoginInfoRes;
   import proto.SpringWelcomeGodInfoRes;
   import proto.SpringGetGodRewardRes;
   import proto.SpringWelfareInfoRes;
   import proto.SpringFireCrackerRes;
   import proto.SpringFightBossStartRes;
   import proto.SpringFightBossEndRes;
   import proto.SpringBeatBossLastRankRes;
   import proto.SpringGetBeatBossRankRewardRes;
   import proto.SpringBeatBossRankListRes;
   import proto.SpringBeatBossNumRes;
   import proto.ActivityDropStaticNotify;
   import proto.PlayerPvpRes;
   import proto.QqDayInviteRewardInfoRes;
   import proto.QqGetDayInviteRewardRes;
   import proto.FamilyExpeInfoRes;
   import proto.FamilyExpeTaskNotify;
   import proto.FamilyExpeLastChampionRes;
   import proto.FamilyExpeStartNotify;
   import proto.FamilyExpeChallengeInfoRes;
   import proto.FamilyExpeFightRes;
   import proto.FamilyExpeFightStartRes;
   import proto.FamilyExpeFightEndRes;
   import proto.FamilyExpeEndNotify;
   import proto.FamilyExpeGetConRankRes;
   import proto.FamilyExpeCrossRankRes;
   import proto.FamilyExpeSingleRankRes;
   import proto.FamilyExpeFamilyPlayerRankRes;
   import proto.FamilyExpeBattleInfoRes;
   import proto.FamilyExpeChampionThroneRes;
   import proto.FamilyExpeBattleReportRes;
   import proto.FamilyExpeDataNotify;
   import proto.SwapActionsInBatchRes;
   import proto.GetSerialNumberRes;
   import proto.FacebookInviteRes;
   import proto.RetrivalInfoRes;
   import proto.GetOpActivityStaticRes;
   import proto.OpActivityStaticNotify;
   import proto.TuanGouInfoRes;
   import proto.TuanGouInfoNotify;
   import proto.TuanGouScoreInfoRes;
   import proto.SupportInfoNotify;
   import proto.FamilyHeroDonationPanelRes;
   import proto.FamilyHeroDonationLaunchRes;
   import proto.FamilyHeroDonationDonateRes;
   import proto.FamilyHeroDonationReceiveRes;
   import proto.FamilyHeroDonationNotify;
   import proto.PetInfoNotify;
   import proto.PetGradeUpRes;
   import proto.PetInfoRes;
   import proto.MjtxInfoRes;
   import proto.MjtxRankRes;
   import proto.MjtxFightStartRes;
   import proto.MjtxFightEndRes;
   import proto.MjtxAutoFightRes;
   import proto.MjtxSomeCountNotify;
   import proto.MjtxOpenBoxRes;
   import proto.FundInfoRes;
   import proto.HeroSkinInfoRes;
   import proto.BuyDoublePanelRes;
   import proto.BuyDoubleBuyRes;
   import proto.FashionMakeRes;
   import proto.FashionXiLianRes;
   import proto.CteamArenaInfoRes;
   import proto.CteamArenaEnemyChangeNotify;
   import proto.CteamArenaStateRes;
   import proto.CteamArenaRankRes;
   import proto.CteamArenaFightRes;
   import proto.CteamArenaPreReportRes;
   import proto.CteamArenaFinalReportRes;
   import proto.CteamPlayerInfoRes;
   import proto.CteamArenaFinalTeamRes;
   import proto.CteamArenaFinalBetInfoRes;
   import proto.CteamArenaHonorRes;
   import proto.HeroShopShardLockRes;
   import proto.MineSweepAllInfoRes;
   import proto.MineSweepPanelRes;
   import proto.MineSweepResetRes;
   import proto.MineSweepOneKeyRes;
   import proto.MineSweepShopInfoRes;
   import proto.MineSweepBuyRes;
   import proto.MineSweepDigRes;
   import proto.MineSweepRankTableRes;
   import proto.MineSweepSingleRewardRes;
   import proto.CrossArenaSelectCountryRes;
   import proto.MineAreaInfoRes;
   import proto.MineHillInfoRes;
   import proto.MineFightRes;
   import proto.MineInfoNotify;
   import proto.GetMineInfoRes;
   import proto.GetEnemyInfoRes;
   import proto.MineInviteInfoRes;
   import proto.MineEventNotify;
   import proto.MineTimesRes;
   import proto.MineLogRes;
   import proto.TowerInfoRes;
   import proto.TowerRankRes;
   import proto.TowerJumpRes;
   import proto.TowerBuyRes;
   import proto.QuestionIsFinishRes;
   import proto.QuestionPanelRes;
   import proto.QuestionSubmitRes;
   import proto.ZhuanpanCrossInfoRes;
   import proto.ZhuanpanCrossRankRes;
   import proto.ZhuanpanCrossSuperRes;
   import proto.ZhuanpanCrossRotateRes;
   import proto.ZhuanpanCrossBuyRes;
   import proto.GetCommentInfoRes;
   import proto.DragonBoatAllInfoRes;
   import proto.DragonBoatMakePanelRes;
   import proto.DragonBoatDonatePanelRes;
   import proto.DragonBoatShopInfoRes;
   import proto.DragonBoatBuyRes;
   import proto.DragonBoatMakeItemRes;
   import proto.DragonBoatOneKeyMakeRes;
   import proto.DragonBoatRankTableRes;
   import proto.DragonBoatSingleRewardRes;
   import proto.DragonBoatDonateRes;
   
   public class CmdResHash extends DictHash
   {
       
      
      public function CmdResHash()
      {
         super();
         this.put(2005,GetPlayerOnlineDataRes);
         this.put(6288,FashionListRes);
         this.put(7440,XunleiJinzuanInfoNotify);
         this.put(7425,FunctionActionNotify);
         this.put(7089,SaddleHorseNotify);
         this.put(2013,BattleSvrCloseNotify);
         this.put(4,TestRes);
         this.put(2008,OnlineSceneNotify);
         this.put(2022,TeamListRes);
         this.put(2020,TeamCreateRes);
         this.put(2021,TeamCreateNotify);
         this.put(2038,TeamInvitedNotify);
         this.put(2026,TeamEnterNotify);
         this.put(2039,TeamMemInfoNotify);
         this.put(2027,TeamGetInfoRes);
         this.put(2037,TeamMemberSynNotify);
         this.put(2028,TeamInfoNotify);
         this.put(2035,TeamCountChangeNotify);
         this.put(2040,TeamReadyNotify);
         this.put(2024,TeamKickNotify);
         this.put(2041,TeamPwdNotify);
         this.put(2042,TeamChangeheroNotify);
         this.put(2043,TeamStartNotify);
         this.put(2045,TeamBuzhenNotify);
         this.put(2031,TeamLeaveNotify);
         this.put(2033,TeamReplyRes);
         this.put(2034,TeamReplyNotify);
         this.put(2047,TeamDismissNotify);
         this.put(2049,TeamStopNotify);
         this.put(2054,TeamChangeNameNotify);
         this.put(2052,BattleTestRes);
         this.put(2053,BattleTestStartNotify);
         this.put(2050,BattleActionNotify);
         this.put(2012,SystemSettingsNotify);
         this.put(1,HeartBeat);
         this.put(2,ProtocolStatusRes);
         this.put(2004,RandomNameRes);
         this.put(2009,PlayerLevelVipInfoNotify);
         this.put(2015,ClientLoadFinishRes);
         this.put(2006,WearChangeNotify);
         this.put(2003,PlayerInfoNotify);
         this.put(8004,PlayerDataNotify);
         this.put(8003,EnterScenePlayerNotify);
         this.put(8001,EnterSceneOtherPlayerNotify);
         this.put(8002,LeaveSceneNotify);
         this.put(6051,ShowLineStateRes);
         this.put(6052,ShowLineNumberRes);
         this.put(8053,StageFightStartRes);
         this.put(8059,StagePhaseCheckRes);
         this.put(8054,StageFightEndRes);
         this.put(8062,EliteInvadeFightStartRes);
         this.put(8063,EliteInvadeFightEndRes);
         this.put(8055,GetStageInfosRes);
         this.put(8064,EliteInvadeNotify);
         this.put(8056,GetChapterInfosRes);
         this.put(8058,StageSaoDangRes);
         this.put(8005,TestDropGroupRes);
         this.put(4010,NormalBagRes);
         this.put(4020,EquipBagRes);
         this.put(4023,ShowItemRes);
         this.put(5010,PanelViewRes);
         this.put(5012,ExpHeroesRes);
         this.put(5001,HeroAddExpRes);
         this.put(5007,BaseProp);
         this.put(5009,HeroShengjieRes);
         this.put(5014,HeroShengjieRecordRes);
         this.put(5011,HeroInfoNotify);
         this.put(5018,HeroAllInfoNotify);
         this.put(5020,BuZhenInfo);
         this.put(5030,BuZhenViewRes);
         this.put(5032,BuZhenListRes);
         this.put(5031,BuZhenSupportRes);
         this.put(7461,LuckTreeWorldExpNotify);
         this.put(7460,LuckTreeGetRewardRes);
         this.put(7462,LuckTreeDajiangNotify);
         this.put(7459,LuckTreeBuyRes);
         this.put(7458,LuckTreeCheerRes);
         this.put(7457,LuckTreeInfoRes);
         this.put(7456,ZhuanPanDajiangRes);
         this.put(7455,ZhuanPanRankDataRes);
         this.put(7453,ZhuanPanBuyRes);
         this.put(7451,ZhuanPanCommonRes);
         this.put(7452,ZhuanPanSuperRes);
         this.put(7450,ZhuanPanInfoRes);
         this.put(7439,XunleiJinzuanGetRewardRes);
         this.put(7437,OpenChallengeNotify);
         this.put(7436,OpenChallengeInfoRes);
         this.put(7435,OpenChallengeGetRewardRes);
         this.put(7434,ShunWangGetRewardRes);
         this.put(7429,JueRoadInfoRes);
         this.put(7430,JueRoadFightStartRes);
         this.put(7432,JueRoadSaoDangRes);
         this.put(7431,JueRoadFightEndRes);
         this.put(7433,JueRoadGetRewardRes);
         this.put(7438,JueRoadRecordRes);
         this.put(7426,ShenGridInfoRes);
         this.put(7427,ShenGridClickRes);
         this.put(7428,ShenGridChooseRes);
         this.put(7323,WeixinGetRewardNotify);
         this.put(7324,WeixinGetRewardRes);
         this.put(7320,MobileCheckGetCodeRes);
         this.put(7321,MobileCheckRes);
         this.put(7322,MobileCheckGetRewardRes);
         this.put(7424,DuowanNewerCardRes);
         this.put(7423,SougouGetRewardRes);
         this.put(7422,SougouInputGetRewardRes);
         this.put(7420,PrivilegeWeiShiCheckRes);
         this.put(7415,OpenFundInfoRes);
         this.put(7416,OpenFundBuyFundRes);
         this.put(7417,OpenFundGetFundRewardRes);
         this.put(7418,OpenFundGetWelfareRes);
         this.put(7419,OpenFundWelfareNotify);
         this.put(7421,SuperSaleResetNotify);
         this.put(7414,SuperSaleRechargeExtraRewardNotify);
         this.put(7410,SuperSaleInfoRes);
         this.put(7411,SuperSaleGetRewardRes);
         this.put(7412,SuperSaleBuyItemRes);
         this.put(7413,SuperSaleAllCountNotify);
         this.put(7405,ActivateCodeRes);
         this.put(7201,HeroPracticeInfoRes);
         this.put(7202,HeroPracticeEnterNodeRes);
         this.put(7203,HeroPracticeFightStartRes);
         this.put(7204,HeroPracticeFightEndRes);
         this.put(7207,HeroPracticeSaoDangRes);
         this.put(7205,HeroPracticeTimesNotify);
         this.put(7206,HeroPracticeResetNotify);
         this.put(7001,PlayerMoveNotify);
         this.put(7012,PlayerMilitaryrankUpgradeRes);
         this.put(7017,PlayerMilitaryrankInfoRes);
         this.put(7024,PlayerFriendApplyRes);
         this.put(7020,PlayerFriendApplyNotify);
         this.put(7036,PlayerDeleteFriendRes);
         this.put(7037,PlayerDeleteFriendNotify);
         this.put(7013,PlayerFriendSearchRes);
         this.put(7014,PlayerFriendRecommendRes);
         this.put(7016,PlayerFriendNextRes);
         this.put(7048,PlayerFriendsInfoRes);
         this.put(7055,PlayerSeeFriendInfoRes);
         this.put(7063,PlayerApplyAgreeRes);
         this.put(7062,PlayerApplyAgreeNotify);
         this.put(7067,PlayerFriendChatNotify);
         this.put(7065,PlayerApplyRefuseNotify);
         this.put(7058,PlayerApplyRefusePiLiangRes);
         this.put(7068,PlayerApplyPiLiangRes);
         this.put(7056,PlayerApplyAgreePiLiangRes);
         this.put(7051,PlayerOnlineNotify);
         this.put(7052,PlayerOfflineNotify);
         this.put(7038,PlayerAddToHeiMingDanRes);
         this.put(7039,PlayerRemoveHeiMingDanRes);
         this.put(7304,FriendSignatureRes);
         this.put(7305,FriendSignatureNotify);
         this.put(7302,FriendDonateStaminaRes);
         this.put(7308,FriendDonateStaminaAllRes);
         this.put(7306,FriendStaminaGetRes);
         this.put(7307,FriendStaminaGetAllRes);
         this.put(7303,FriendDonateStaminaNotify);
         this.put(7301,FriendTrendsRes);
         this.put(7310,FriendTrendNotify);
         this.put(7069,FriendCongratulateRes);
         this.put(7309,FriendCongratulateAllRes);
         this.put(7300,FriendCongratulateNotify);
         this.put(7312,FriendStaminaInfoRes);
         this.put(7311,FriendDailyInfoClearNotify);
         this.put(7070,PlayerActivateSaddleHorseRes);
         this.put(7071,PlayerUseSaddleHorseRes);
         this.put(7072,PlayerUnuseSaddleHorseRes);
         this.put(7073,PlayerChangeSaddleHorseRes);
         this.put(7075,PlayerChangeGloryRes);
         this.put(7077,PlayerGetSaddleHorsesRes);
         this.put(7079,PlayerGetGloriesRes);
         this.put(7083,PlayerGetCurrentSaddleHorseRes);
         this.put(7081,PlayerGetCurrentGloryRes);
         this.put(7088,PlayerSaddleHorseUpgradeRes);
         this.put(7091,PlayerBossZhaoHuanFreeTimeRes);
         this.put(7090,PlayerBossZhaoHuanRes);
         this.put(7085,PlayerSaddleHorseYanJiuRes);
         this.put(7087,PlayerSaddleHorseYanJiuOneKeyRes);
         this.put(7005,PlayerResStageFightEndRes);
         this.put(7511,WorldBossStartEventNotify);
         this.put(7513,WorldBossNextWaveNotify);
         this.put(7508,WorldBossMemberReliveNotify);
         this.put(7500,WorldBossInfoRes);
         this.put(7518,WorldBossQuickFightStartRes);
         this.put(7512,WorldBossTopRankNotify);
         this.put(7514,WorldBossInfoNotify);
         this.put(7509,WorldBossMemberDeadNotify);
         this.put(7503,WorldBossHurtInfoRes);
         this.put(7517,WorldBossHurtRewardRes);
         this.put(7515,WorldBossJoinFightStartRes);
         this.put(7516,WorldBossModelSetRes);
         this.put(7189,FamilyBossSupperRankRes);
         this.put(7188,FamilyBossQuickFightStartRes);
         this.put(7187,FamilyBossHurtRewardRes);
         this.put(7184,FamilyBossInfoNotify);
         this.put(7183,FamilyBossNextWaveNotify);
         this.put(7182,FamilyBossTopRankNotify);
         this.put(7181,FamilyBossStartEventNotify);
         this.put(7180,FamilyBossNextStartTimeNotify);
         this.put(7170,FamilyBossInfoRes);
         this.put(7171,FamilyBossSetNextStartTimeRes);
         this.put(7172,FamilyBossBuyGuliRes);
         this.put(7173,FamilyBossHurtInfoRes);
         this.put(7174,FamilyBossModelSetRes);
         this.put(7175,FamilyBossReliveRes);
         this.put(7178,FamilyBossMemberReliveNotify);
         this.put(7179,FamilyBossMemberDeadNotify);
         this.put(7176,FamilyBossJoinFightStartRes);
         this.put(7177,FamilyBossJoinFightEndRes);
         this.put(7185,FamilyBossBossReliveNotify);
         this.put(7186,FamilyBossBossBuffNotify);
         this.put(7144,FamilyStageChapterSelectRes);
         this.put(7145,FamilyStageGetRewardRes);
         this.put(7146,FamilyStageChapterSelectNotify);
         this.put(7147,FamilyStageGetRewardNotify);
         this.put(7148,FamilyStageRewardInfoRes);
         this.put(7149,FamilyStageRecordRes);
         this.put(7150,FamilyStageEnterChapterRes);
         this.put(7151,FamilyStageFightStartRes);
         this.put(7152,FamilyStageFightEndRes);
         this.put(7153,FamilyStageYuKouStartRes);
         this.put(7154,FamilyStageYuKouEndRes);
         this.put(7163,FamilyStageYuKouSaoDangRes);
         this.put(7155,FamilyStageHurtRankRes);
         this.put(7156,FamilyStageHpsNotify);
         this.put(7157,FamilyStageResetNotify);
         this.put(7158,FamilyStageFightStartNotify);
         this.put(7159,FamilyStageFightEndNotify);
         this.put(7160,FamilyStageNodeRankRes);
         this.put(7161,FamilyStageBuyTimesRes);
         this.put(7162,FamilyStageTimesNotify);
         this.put(7401,FamilyTechInfoRes);
         this.put(7402,FamilyTechResearchRes);
         this.put(7403,FamilyTechStudyRes);
         this.put(7404,FamilyTechResearchNotify);
         this.put(8104,EquipPanelViewRes);
         this.put(8100,EquipStrengthRes);
         this.put(8101,EquipJinglianRes);
         this.put(6602,EquipAddStarRes);
         this.put(6001,PublicTalkNotify);
         this.put(6003,EventNotify);
         this.put(6004,PublicTalkMultiNotify);
         this.put(6002,PrivateTalkNotify);
         this.put(2014,PTChatPlayerInfoRes);
         this.put(2010,PTChatPlayerInfoRes);
         this.put(5201,FamilyInfoRes);
         this.put(5202,FamilyApplyRes);
         this.put(5224,FamilyOtherRes);
         this.put(5209,FamilyQuitRes);
         this.put(5211,FamilyInfoRes);
         this.put(5212,FamilyMemberRes);
         this.put(5218,FamilyApplyListRes);
         this.put(5213,FamilyListRes);
         this.put(5214,FamilyDonateRes);
         this.put(5230,FamilyDonateRes);
         this.put(5215,FamilyChangeNoticeRes);
         this.put(5217,FamilyLogRes);
         this.put(5220,FamilyApplyNotify);
         this.put(5227,FamilyGetAuthorityRes);
         this.put(5223,FamilyMemberInfoRes);
         this.put(5228,FamilyAuthorityNotify);
         this.put(5229,FamilyDonateScoreRes);
         this.put(8155,DelMailNotify);
         this.put(8150,GetMailListRes);
         this.put(8151,ReadMailRes);
         this.put(8156,GetMailRewardRes);
         this.put(8153,DelMailRes);
         this.put(8154,MailNotify);
         this.put(8157,NewGroupMailNotify);
         this.put(5100,BaoWuBagRes);
         this.put(5102,BaoWuStrengthRes);
         this.put(5103,BaoWuKeyinRes);
         this.put(5115,BaoWuKeyinRes);
         this.put(5104,BaoWuFumoRes);
         this.put(5105,BaoWuFumoOpenRes);
         this.put(5109,BaoWuMoshiAllRes);
         this.put(5110,MoShiCombineRecordRes);
         this.put(5108,BaoWuFumoAllRes);
         this.put(5112,BaoWuGoldCombineRes);
         this.put(5114,BaoWuPurifyRes);
         this.put(5113,BaoWuRemouldRes);
         this.put(6073,GetShenYuanInfoRes);
         this.put(6086,ShenYuanReceiveBoxRes);
         this.put(6075,ShenYuanGetMysteriBoxRes);
         this.put(6076,ShenYuanTongGuanRes);
         this.put(6077,ShenYuanRequestFriendRes);
         this.put(6078,FightShenYuanStartRes);
         this.put(6079,FightShenYuanEndRes);
         this.put(6083,ShenYuanBuyBuffRes);
         this.put(6081,ShenYuanPaiMingRes);
         this.put(6085,ShenYuanRankRewardRes);
         this.put(6088,ShenYuanGetLuckyBoxRes);
         this.put(4000,LotteryInfoRes);
         this.put(4001,LotteryRandRes);
         this.put(3000,LotterySuperRes);
         this.put(7200,LotteryGetRewardRes);
         this.put(3153,GuajiSaoDangRes);
         this.put(3150,GuajiPvpBeStealNotify);
         this.put(3020,GuajiInfoRes);
         this.put(3029,GuajiInfoNotify);
         this.put(3022,GuajiBossFightStartRes);
         this.put(3023,GuajiBossFightEndRes);
         this.put(3024,GuajiGetBagInfoRes);
         this.put(3026,GuajiExtraRewardNotify);
         this.put(3027,GuajiLogRes);
         this.put(3152,GuajiSwitchNotify);
         this.put(3031,GuajiFightStNotify);
         this.put(3032,GuajiRewardDispNotify);
         this.put(3140,GuajiChangePvperRes);
         this.put(3143,GuajiPvpFightStartRes);
         this.put(3151,GuajiPvpAutoFightRes);
         this.put(3144,GuajiPvpFightEndRes);
         this.put(3145,GuajiPvpTodayRankRes);
         this.put(3146,GuajiPvpYestodayRankRes);
         this.put(3033,CrossSceneWatchRes);
         this.put(3036,CrossSceneEnterNotify);
         this.put(3037,CrossSceneLeaveNotify);
         this.put(3148,GuajiSomeDataNotify);
         this.put(8201,BtlAddBuffNotify);
         this.put(8202,BtlDelBuffNotify);
         this.put(8200,BtlSkillNotify);
         this.put(8203,BtlPlayerDeadNotify);
         this.put(8204,BtlPlayerReviveNotify);
         this.put(8205,BtlNpcHpNotify);
         this.put(6068,StageBtlGuideRes);
         this.put(5304,ClothesSkillBagRes);
         this.put(5301,ClothesBagRes);
         this.put(5305,ClothesActiveRes);
         this.put(6136,GetYunBiaoStateRes);
         this.put(6148,RefreshYunBiaoShipQualityRes);
         this.put(6138,GetYunBiaoFlyInfoRes);
         this.put(6146,ShowYunBiaoDaJieInfoRes);
         this.put(6147,YunBiaoDaJieRes);
         this.put(3041,ShopBuyRes);
         this.put(3042,ShopRefreshRes);
         this.put(3040,ShopListRes);
         this.put(3043,MallListRes);
         this.put(3044,MallBuyRes);
         this.put(3045,MallNotify);
         this.put(8300,TaskGetCurInfoRes);
         this.put(8302,TaskInfoNotify);
         this.put(8350,ActivityGetInfosRes);
         this.put(8353,ActivityRewardNotify);
         this.put(8354,StaticActivitysRes);
         this.put(8360,ActivityHotUpdateNotify);
         this.put(5310,ViewOtherPlayerRes);
         this.put(4030,ArenaInfoRes);
         this.put(4039,ArenaReportInfoRes);
         this.put(4031,ArenaChallengeRes);
         this.put(4040,ArenaMultiChallengeRes);
         this.put(4033,ArenaClearCdDiamondRes);
         this.put(4034,ArenaBuyTimesRes);
         this.put(4036,ArenaChangeEnemyRes);
         this.put(4037,ArenaGetRankRewardRes);
         this.put(4038,ArenaGetRankListRes);
         this.put(4042,ArenaReportNotify);
         this.put(5330,RecycleHeroDecomposeRes);
         this.put(5331,RecycleEquipDecomposeRes);
         this.put(5332,RecycleBaowuDecomposeRes);
         this.put(5334,RecyclePetDecomposeRes);
         this.put(5336,GetTimesBuyRes);
         this.put(8007,GetSwapActionsRes);
         this.put(6210,AbilityRankRes);
         this.put(6213,LevelRankRes);
         this.put(6212,FamilyRankRes);
         this.put(6211,AreaRankRes);
         this.put(6214,StageStarRankRes);
         this.put(6215,RankSearchNameRes);
         this.put(2007,SystemTimeNotify);
         this.put(4050,CompeteInfoRes);
         this.put(4053,CompeteGroupStageInfoRes);
         this.put(4054,CompeteStatusTimeNotify);
         this.put(4051,CompetePlayerDisplayRes);
         this.put(4052,CompeteStageInfoRes);
         this.put(4055,CompeteGambleInfoRes);
         this.put(4057,CompeteGambleRewardRes);
         this.put(4059,CompetePlayerRankInfoRes);
         this.put(4061,CompeteOpenTimeRes);
         this.put(4101,FunctionOpenTimeNotify);
         this.put(4102,FunctionTimesNotify);
         this.put(6300,GetSignInInfoRes);
         this.put(6302,CanSignInRes);
         this.put(6301,SignInRes);
         this.put(6304,CanGetSignInExtraRes);
         this.put(6303,SignInExtraRes);
         this.put(4070,SevenDayInfoRes);
         this.put(6231,FourteenInfoRes);
         this.put(4073,SevenDayTimeStampRes);
         this.put(4074,SevenDayShopSellOutNotify);
         this.put(4075,SevenDayAvaiNumRes);
         this.put(4200,BgInfoRes);
         this.put(4201,BgTeamInfoRes);
         this.put(4202,BgTeamNewMemNotify);
         this.put(4203,BgTeamMemInfoNotify);
         this.put(4205,BgRegNotify);
         this.put(4207,BgLeaveNotify);
         this.put(4208,BgBtlLeaveNotify);
         this.put(4211,BgCheckRes);
         this.put(4212,BgTeamDismissNotify);
         this.put(4214,BgFriendsListRes);
         this.put(4215,BgFamilyMemberListRes);
         this.put(4217,BgFightNotify);
         this.put(4239,BgFightNpcRes);
         this.put(4240,BgFightNpcNotify);
         this.put(4219,BgGatherNotify);
         this.put(4233,BgGatherStatusNotify);
         this.put(4227,BgResStatusNotify);
         this.put(4228,BgStageGetReportRes);
         this.put(4301,CrossSceneMoveNotify);
         this.put(4220,BgStageEnterNotify);
         this.put(4221,BgStageNewEnterNotify);
         this.put(4229,BgCryStageInfoNotify);
         this.put(4237,BgFireStageInfoNotify);
         this.put(4230,BgStageEndNotify);
         this.put(4222,BgDeadNotify);
         this.put(4223,BgRebornNotify);
         this.put(4224,BgPlayerStatusNotify);
         this.put(4226,BgSceneMoveNotify);
         this.put(4232,BgStageLeaveNotify);
         this.put(4235,BgGetTitleRewardInfoRes);
         this.put(4236,BgGetRankInfoRes);
         this.put(4209,BgStartNotify);
         this.put(4238,BgPlaceFlagNotify);
         this.put(4302,CardInfoNotify);
         this.put(4250,BkInfoRes);
         this.put(4252,BkRegNotify);
         this.put(4254,BkLeaveNotify);
         this.put(4255,BkBtlLeaveNotify);
         this.put(4258,BkCheckRes);
         this.put(4276,BkSpecialCommandRes);
         this.put(4277,BkSpecialCommandNotify);
         this.put(4261,BkFightNotify);
         this.put(4269,BkResStatusNotify);
         this.put(4270,BkStageGetReportRes);
         this.put(4262,BkStageEnterNotify);
         this.put(4263,BkStageNewEnterNotify);
         this.put(4274,BkGameStageInfoNotify);
         this.put(4275,BkGameStepNotify);
         this.put(4271,BkStageEndNotify);
         this.put(4264,BkDeadNotify);
         this.put(4265,BkRebornNotify);
         this.put(4266,BkPlayerStatusNotify);
         this.put(4268,BkSceneMoveNotify);
         this.put(4273,BkStageLeaveNotify);
         this.put(4256,BkStartNotify);
         this.put(6401,GetVipInfoRes);
         this.put(6403,GetVipRewardInfoRes);
         this.put(6402,GetChargeInfoRes);
         this.put(6404,VipReceiveChargeRewardRes);
         this.put(6405,VipGetFirstChargeRes);
         this.put(6505,VipMonthCardRes);
         this.put(6406,VipGetFirstChargeRewardRes);
         this.put(8411,CwPlayerInfoRes);
         this.put(8401,CwCandidateListRes);
         this.put(8405,CwShowGeneralRes);
         this.put(8406,CwRandCampRes);
         this.put(8407,CwCampListRes);
         this.put(8408,CwCampDetailInfoRes);
         this.put(8410,CwShowMarshalRes);
         this.put(8500,GetAuctionListRes);
         this.put(8501,AuctionSellItemRes);
         this.put(8502,AuctionUnsellItemRes);
         this.put(8503,AuctionBuyItemRes);
         this.put(8507,AuctionMyListStatNotify);
         this.put(8504,AuctionMyOrderRes);
         this.put(8505,AuctionMySellsRes);
         this.put(5111,BaoWuStatNotify);
         this.put(2100,QqAddgoodsRes);
         this.put(2106,QqGetTokenRes);
         this.put(2105,QqGiftInfoRes);
         this.put(6603,WeiDuanGetRewardRes);
         this.put(4310,CrossArenaInfoRes);
         this.put(4324,CrossArenaUpdateFinalEnemyRes);
         this.put(4311,CrossArenaFightRes);
         this.put(4313,CrossArenaChangeEnemyRes);
         this.put(4315,CrossArenaRankInfoRes);
         this.put(4316,CrossArenaSomeDataNotify);
         this.put(4319,CrossArenaCheerRes);
         this.put(4318,CrossArenaCheerInfoRes);
         this.put(4323,CrossArenaHonorHallRes);
         this.put(4320,CrossArenaFinalFightRes);
         this.put(4321,CrossArenaGetReportRes);
         this.put(4322,CrossArenaDistCheerRes);
         this.put(6701,ActiveTitleRes);
         this.put(6703,TitleChangeNotify);
         this.put(6702,TitlePanelRes);
         this.put(6704,WearTitleRes);
         this.put(6230,FourteenDayNotify);
         this.put(6234,FourteenDayShopBuyTimesRes);
         this.put(6252,ValentineShopInfoRes);
         this.put(6271,WhiteValentineShopInfoRes);
         this.put(6258,LanternShopInfoRes);
         this.put(10011,CharmRankStunnerRes);
         this.put(10012,CharmRankReceiveMessageRes);
         this.put(10014,CharmRankShopInfoRes);
         this.put(10015,CharmRankShopDetailRes);
         this.put(10016,CharmRankRankDetailRes);
         this.put(6268,WhiteValentineStunnerRes);
         this.put(6269,WhiteValentineReceiveMessageRes);
         this.put(6259,GoddessVotePanelRes);
         this.put(6260,GoddessVoteRes);
         this.put(6262,GoddessScorePanelRes);
         this.put(6261,GoddessShowPanelRes);
         this.put(6242,SpringLoginInfoRes);
         this.put(6243,SpringWelcomeGodInfoRes);
         this.put(6244,SpringGetGodRewardRes);
         this.put(6245,SpringWelfareInfoRes);
         this.put(6247,SpringFireCrackerRes);
         this.put(6250,SpringFightBossStartRes);
         this.put(6251,SpringFightBossEndRes);
         this.put(6255,SpringBeatBossLastRankRes);
         this.put(6254,SpringGetBeatBossRankRewardRes);
         this.put(6246,SpringBeatBossRankListRes);
         this.put(6253,SpringBeatBossNumRes);
         this.put(8520,ActivityDropStaticNotify);
         this.put(8521,PlayerPvpRes);
         this.put(2108,QqDayInviteRewardInfoRes);
         this.put(2109,QqGetDayInviteRewardRes);
         this.put(4350,FamilyExpeInfoRes);
         this.put(4362,FamilyExpeTaskNotify);
         this.put(4367,FamilyExpeLastChampionRes);
         this.put(4352,FamilyExpeStartNotify);
         this.put(4353,FamilyExpeChallengeInfoRes);
         this.put(4358,FamilyExpeFightRes);
         this.put(4354,FamilyExpeFightStartRes);
         this.put(4355,FamilyExpeFightEndRes);
         this.put(4360,FamilyExpeEndNotify);
         this.put(4359,FamilyExpeGetConRankRes);
         this.put(4363,FamilyExpeCrossRankRes);
         this.put(4366,FamilyExpeSingleRankRes);
         this.put(4365,FamilyExpeFamilyPlayerRankRes);
         this.put(4364,FamilyExpeBattleInfoRes);
         this.put(4368,FamilyExpeChampionThroneRes);
         this.put(4369,FamilyExpeBattleReportRes);
         this.put(4370,FamilyExpeDataNotify);
         this.put(8009,SwapActionsInBatchRes);
         this.put(10000,GetSerialNumberRes);
         this.put(10001,FacebookInviteRes);
         this.put(5370,RetrivalInfoRes);
         this.put(8530,GetOpActivityStaticRes);
         this.put(8531,OpActivityStaticNotify);
         this.put(8532,TuanGouInfoRes);
         this.put(8533,TuanGouInfoNotify);
         this.put(8537,TuanGouScoreInfoRes);
         this.put(5340,SupportInfoNotify);
         this.put(10020,FamilyHeroDonationPanelRes);
         this.put(10021,FamilyHeroDonationLaunchRes);
         this.put(10022,FamilyHeroDonationDonateRes);
         this.put(10023,FamilyHeroDonationReceiveRes);
         this.put(10024,FamilyHeroDonationNotify);
         this.put(5361,PetInfoNotify);
         this.put(5362,PetGradeUpRes);
         this.put(5367,PetInfoRes);
         this.put(8600,MjtxInfoRes);
         this.put(8601,MjtxRankRes);
         this.put(8603,MjtxFightStartRes);
         this.put(8604,MjtxFightEndRes);
         this.put(8605,MjtxAutoFightRes);
         this.put(8607,MjtxSomeCountNotify);
         this.put(8602,MjtxOpenBoxRes);
         this.put(8620,FundInfoRes);
         this.put(5022,HeroSkinInfoRes);
         this.put(10030,BuyDoublePanelRes);
         this.put(10031,BuyDoubleBuyRes);
         this.put(6284,FashionMakeRes);
         this.put(6285,FashionXiLianRes);
         this.put(5405,CteamArenaInfoRes);
         this.put(5406,CteamArenaEnemyChangeNotify);
         this.put(5408,CteamArenaStateRes);
         this.put(5404,CteamArenaRankRes);
         this.put(5402,CteamArenaFightRes);
         this.put(5409,CteamArenaPreReportRes);
         this.put(5410,CteamArenaFinalReportRes);
         this.put(5411,CteamPlayerInfoRes);
         this.put(5413,CteamArenaFinalTeamRes);
         this.put(5414,CteamArenaFinalBetInfoRes);
         this.put(5417,CteamArenaHonorRes);
         this.put(10032,HeroShopShardLockRes);
         this.put(6281,MineSweepAllInfoRes);
         this.put(6273,MineSweepPanelRes);
         this.put(6275,MineSweepResetRes);
         this.put(6276,MineSweepOneKeyRes);
         this.put(6282,MineSweepShopInfoRes);
         this.put(6280,MineSweepBuyRes);
         this.put(6277,MineSweepDigRes);
         this.put(6278,MineSweepRankTableRes);
         this.put(6279,MineSweepSingleRewardRes);
         this.put(10033,CrossArenaSelectCountryRes);
         this.put(5441,MineAreaInfoRes);
         this.put(5442,MineHillInfoRes);
         this.put(5444,MineFightRes);
         this.put(5449,MineInfoNotify);
         this.put(5447,GetMineInfoRes);
         this.put(5452,GetEnemyInfoRes);
         this.put(5453,MineInviteInfoRes);
         this.put(5454,MineEventNotify);
         this.put(5456,MineTimesRes);
         this.put(5457,MineLogRes);
         this.put(2190,TowerInfoRes);
         this.put(2191,TowerRankRes);
         this.put(2192,TowerJumpRes);
         this.put(2195,TowerBuyRes);
         this.put(10040,QuestionIsFinishRes);
         this.put(10041,QuestionPanelRes);
         this.put(10042,QuestionSubmitRes);
         this.put(6290,ZhuanpanCrossInfoRes);
         this.put(6291,ZhuanpanCrossRankRes);
         this.put(6293,ZhuanpanCrossSuperRes);
         this.put(6292,ZhuanpanCrossRotateRes);
         this.put(6294,ZhuanpanCrossBuyRes);
         this.put(10034,GetCommentInfoRes);
         this.put(6350,DragonBoatAllInfoRes);
         this.put(6351,DragonBoatMakePanelRes);
         this.put(6359,DragonBoatDonatePanelRes);
         this.put(6352,DragonBoatShopInfoRes);
         this.put(6353,DragonBoatBuyRes);
         this.put(6354,DragonBoatMakeItemRes);
         this.put(6355,DragonBoatOneKeyMakeRes);
         this.put(6356,DragonBoatRankTableRes);
         this.put(6357,DragonBoatSingleRewardRes);
         this.put(6360,DragonBoatDonateRes);
      }
      
      public function getResClass(param1:int) : Class
      {
         return this.getValue(param1) as Class;
      }
      
      public function createRes(param1:int) : Message
      {
         var _loc2_:Class = getResClass(param1);
         return new _loc2_();
      }
   }
}
