package nslm2.inits
{
   import com.mz.core.utils2.task.TaskBase;
   import morn.core.components.View;
   import game.ui.commons.comps.others.NewerGuideCommonRenderUI;
   import nslm2.modules.footstones.newerGuideModules.NewerGuideArrow;
   import game.ui.newerGuideModules.NewerGuideSkipUI;
   import nslm2.modules.footstones.newerGuideModules.NewerGuideSkip;
   import game.ui.newerGuideModules.NewerGuideNPCSayUI;
   import nslm2.modules.footstones.newerGuideModules.NewerGuideNPCSay;
   import game.ui.commons.comps.others.RedPointNumUI;
   import nslm2.common.ui.components.comps2d.others.RedPointNum;
   import game.ui.commons.comps.others.RedPointUI;
   import nslm2.common.ui.components.comps2d.others.RedPoint;
   import game.ui.commons.comps.btns.BtnOkUI;
   import nslm2.common.ui.components.comps2d.btns.BtnOK;
   import game.ui.commons.comps.btns.BtnCancelUI;
   import nslm2.common.ui.components.comps2d.btns.BtnCancel;
   import game.ui.commons.comps.others.TaskAlertRenderUI;
   import nslm2.common.ui.components.comps2d.others.TaskAlertRender;
   import game.ui.commons.comps.others.TaskAlertRenderS3UI;
   import nslm2.common.ui.components.comps2d.others.TaskAlertRenderS3;
   import game.ui.miniMaps.MiniMapBtnUI;
   import nslm2.modules.foundations.miniMaps.MiniMapBtn;
   import game.ui.miniMaps.ChangeLineUI;
   import nslm2.modules.foundations.miniMaps.ChangeLine;
   import game.ui.miniMaps.MiniMapLineRenderUI;
   import nslm2.modules.foundations.miniMaps.MiniMapLineRender;
   import game.ui.commons.props.FightValueBoxUI;
   import nslm2.common.ui.components.comps2d.others.FightValueBox;
   import game.ui.commons.props.FightValueBoxS2UI;
   import nslm2.common.ui.components.comps2d.others.FightValueBoxS2;
   import game.ui.commons.props.FightValueBoxS4UI;
   import nslm2.common.ui.components.comps2d.others.FightValueBoxS4;
   import game.ui.commons.comps.others.ClickToNextUI;
   import nslm2.common.ui.components.comps2d.others.ClickToNext;
   import game.ui.commons.comps.others.ClickToNextButtonUI;
   import nslm2.common.ui.components.comps2d.others.ClickToNextButton;
   import game.ui.lotteryHeroModules.ClickToNextButtonTimeUI;
   import nslm2.common.ui.components.comps2d.ClickToNextButtonTime;
   import game.ui.BagModules.BagItemRenderUI;
   import nslm2.modules.bag.BagItemRender;
   import game.ui.BagModules.SellBatchItemRenderUI;
   import nslm2.modules.bag.SellBatchItemRender;
   import game.ui.BagModules.UseGiftRenderUI;
   import nslm2.modules.bag.UseGiftRender;
   import game.ui.BagModules.GetGiftRenderUI;
   import nslm2.modules.bag.GetGiftRender;
   import game.ui.BagModules.SellBatchItemWealthRenderUI;
   import nslm2.modules.bag.SellBatchItemWealthRender;
   import game.ui.BagModules.equipComposes.EquipComposeRenderToUI;
   import nslm2.modules.bag.equipComposes.EquipComposeRenderTo;
   import game.ui.logModules.TestAccordionTitleRenderUI;
   import nslm2.modules.logModules.TestAccordionTitleRender;
   import game.ui.logModules.TestAccordionContentRenderUI;
   import nslm2.modules.logModules.TestAccordionContentRender;
   import game.ui.loadingModules.LoadingSceneUI;
   import nslm2.modules.footstones.loadingModules.LoadingScene;
   import game.ui.loadingModules.LoadingPopUI;
   import nslm2.modules.footstones.loadingModules.LoadingPop;
   import game.ui.tooltipModules.comps.TooltipTxtUI;
   import nslm2.modules.footstones.tooltipsModules.uis.comps.TooltipTxt;
   import game.ui.commons.comps.pageBars.PageBarS1UI;
   import nslm2.common.ui.components.comps2d.pageBar.PageBarS1;
   import game.ui.commons.comps.pageBars.PageBarS2UI;
   import nslm2.common.ui.components.comps2d.pageBar.PageBarS2;
   import game.ui.commons.comps.pageBars.PageBarS3UI;
   import nslm2.common.ui.components.comps2d.pageBar.PageBarS3;
   import game.ui.commons.comps.pageBars.PageBarS4UI;
   import nslm2.common.ui.components.comps2d.pageBar.PageBarS4;
   import game.ui.commons.comps.numBar.NumBarS1UI;
   import nslm2.common.ui.components.comps2d.numBar.NumBarS1;
   import game.ui.commons.comps.btns.BtnRenderUI;
   import morn.customs.components.BtnRender;
   import game.ui.commons.icons.TupoClipRenderUI;
   import morn.customs.components.TupoClipRender;
   import game.ui.commons.icons.PlayerTitleRenderUI;
   import morn.customs.components.PlayerTitleRender;
   import game.ui.resGetPoints.ResGetPointListRenderUI;
   import nslm2.modules.footstones.resGetPoints.ResGetPointListRender;
   import game.ui.resGetPoints.ResGetPointResRenderUI;
   import nslm2.modules.footstones.resGetPoints.ResGetPointResRender;
   import game.ui.roleInfos.RoleSelectListPanelUI;
   import nslm2.modules.roleInfos.RoleSelectListPanel;
   import game.ui.roleInfos.equipPanels.RoleBaoWuRenderUI;
   import nslm2.modules.roleInfos.equipPanels.RoleBaoWuRender;
   import game.ui.roleInfos.equipPanels.RoleDetailPropRenderUI;
   import nslm2.modules.roleInfos.equipPanels.RoleDetailPropListRender;
   import game.ui.roleInfos.equipPanels.YuanFenRenderUI;
   import nslm2.modules.roleInfos.equipPanels.YuanFengListRender;
   import game.ui.roleInfos.equipPanels.BasePropRenderUI;
   import nslm2.modules.roleInfos.equipPanels.RoleBasePropRender;
   import game.ui.roleInfos.phaseUps.SkillShowRenderUI;
   import nslm2.modules.roleInfos.phaseUps.PhaseUpSkillShowRender;
   import game.ui.roleInfos.phaseUps.ShenjieTujianListRenderUI;
   import nslm2.modules.roleInfos.phaseUps.RoleShenjieTujianRender;
   import game.ui.roleInfos.phaseUps.SkillRenderSmallUI;
   import nslm2.modules.roleInfos.phaseUps.SkillRenderSmall;
   import game.ui.roleInfos.equipPanels.DetailYuanfenInfoRenderUI;
   import nslm2.modules.roleInfos.equipPanels.DetailYuanFenRender;
   import game.ui.roleInfos.tupos.TianfuInfoRenderUI;
   import nslm2.modules.roleInfos.tupos.TianfuRender;
   import game.ui.otherRoleInfos.render.OtherRoleEquipRenderUI;
   import nslm2.modules.cultivates.otherRoleInfos.OtherRoleEquipRender;
   import game.ui.otherRoleInfos.render.OtherRoleYuanJunRenderUI;
   import nslm2.modules.cultivates.otherRoleInfos.OtherRoleYuanJunRender;
   import game.ui.otherRoleInfos.render.OtherRoleListRenderUI;
   import nslm2.modules.cultivates.otherRoleInfos.OtherRoleListRender;
   import game.ui.otherRoleInfos.render.OtherRoleListPetRenderUI;
   import nslm2.modules.cultivates.otherRoleInfos.OtherRoleListPetRender;
   import game.ui.chatModules.chatSendBoxes.ChatSendBoxUI;
   import nslm2.modules.foundations.chatModules.chatSendBoxes.ChatSendBox;
   import game.ui.chatModules.chatSendBoxes.ChatFaceSelectPanelUI;
   import nslm2.modules.foundations.chatModules.chatSendBoxes.ChatFaceSelectPanel;
   import game.ui.chatModules.ChatBtnChannelRenderUI;
   import nslm2.modules.foundations.chatModules.ChatBtnChannelRender;
   import game.ui.chatModules.ChatHistoryUI;
   import nslm2.modules.foundations.chatModules.historyPanels.ChatHistory;
   import game.ui.chatModules.ChatHistoryPanelS1UI;
   import nslm2.modules.foundations.chatModules.historyPanels.historyS1.ChatHistoryPanelS1;
   import game.ui.chatModules.ChatHistoryPanelS2UI;
   import nslm2.modules.foundations.chatModules.historyPanels.historyS2.ChatHistoryPanelS2;
   import game.ui.chatModules.ChatHistoryPanelS3UI;
   import nslm2.modules.foundations.chatModules.historyPanels.historyS3.ChatHistoryPanelS3;
   import game.ui.chatModules.localChatHistory.ChatHistoryPanelLocalUI;
   import nslm2.modules.foundations.chatModules.localChatHistory.ChatHistoryPanelLocal;
   import game.ui.chatModules.ChatHistoryHeaderIconUI;
   import nslm2.modules.foundations.chatModules.historyPanels.historyS2.ChatHistoryHeaderIcon;
   import game.ui.chatModules.privChats.PrivChatRoleListUI;
   import nslm2.modules.foundations.chatModules.privChats.PrivChatRoleList;
   import game.ui.chatModules.privChats.PrivChatRoleListRenderUI;
   import nslm2.modules.foundations.chatModules.privChats.PrivChatRoleListRender;
   import game.ui.chatModules.privChats.PrivChatPlayerRenderUI;
   import nslm2.modules.foundations.chatModules.privChats.PrivChatPlayerRender;
   import game.ui.chatModules.privChats.PrivChatRoleListRender_playerUI;
   import nslm2.modules.foundations.chatModules.privChats.PrivChatRoleListRender_player;
   import game.ui.chatModules.privChats.PrivChatHistoryUI;
   import nslm2.modules.foundations.chatModules.privChats.PrivChatHistory;
   import game.ui.chatModules.privChats.PrivChatSendUI;
   import nslm2.modules.foundations.chatModules.privChats.PrivChatSend;
   import game.ui.playerHeaders.PlayerHeaderStaminaBarUI;
   import nslm2.modules.foundations.playerHeaders.PlayerHeaderStaminaBar;
   import game.ui.mainToolBar.ExpBarUI;
   import nslm2.modules.foundations.mainToolBar.ExpBar;
   import game.ui.skillChangePanel.SkillChangeRenderUI;
   import nslm2.modules.cultivates.skillChangePanels.SkillChangeRender;
   import game.ui.skillChangePanel.SkillKindRenderUI;
   import nslm2.modules.cultivates.skillChangePanels.SkillKindRender;
   import game.ui.playerHeaders.PlayerHeaderWealthRenderUI;
   import nslm2.modules.foundations.playerHeaders.PlayerHeaderWealthRender;
   import game.ui.playerHeaders.PlayerHeaderWealthRenderSmallUI;
   import nslm2.modules.foundations.playerHeaders.PlayerHeaderWealthRenderSmall;
   import game.ui.treasures.render.PropRenderUI;
   import nslm2.modules.cultivates.treasure.view.render.PropRender;
   import game.ui.treasures.render.RandomPropRenderUI;
   import nslm2.modules.cultivates.treasure.view.render.RandomPorpRender;
   import game.ui.roleInfos.awake.render.RoleAwakePropRenderUI;
   import nslm2.modules.roleInfos.awake.render.RoleAwakePropRender;
   import game.ui.newYears.valentine2016s.render.ValentineSalesRenderUI;
   import nslm2.modules.funnies.newYears.valentine2016.render.ValentineSalesRender;
   import game.ui.newYears.lantern2016s.render.LanternSalesRenderUI;
   import nslm2.modules.funnies.newYears.lantern2016.render.LanternSalesRender;
   import game.ui.sevenDayModule.view.SevenDaysSaleRenderUI;
   import nslm2.modules.foundations.fourteenDays.render.FourteenDaysSaleRender;
   import game.ui.salesModule.render.SalesPelopleNumRenderUI;
   import nslm2.modules.foundations.sales.render.SalesPelopleNumRender;
   import game.ui.salesModule.render.SalesItemRenderUI;
   import nslm2.modules.foundations.sales.render.SalesItemRender;
   import game.ui.salesModule.render.SalesBenefitRenderUI;
   import nslm2.modules.foundations.sales.render.SalesBenefitRender;
   import game.ui.gameHelpModule.render.GameHelpTitleRenderUI;
   import nslm2.modules.foundations.gameHelp.render.GameHelpTitleRender;
   import game.ui.gameHelpModule.render.GameHelpRenderUI;
   import nslm2.modules.foundations.gameHelp.render.GameHelpRender;
   import game.ui.vipModule.render.ChargeRenderUI;
   import nslm2.modules.foundations.vip.render.ChargeRender;
   import game.ui.vipModule.render.VipPrivilegeRenderUI;
   import nslm2.modules.foundations.vip.render.VipPrivilegeRender;
   import game.ui.vipModule.render.VipPrivilegesRenderUI;
   import nslm2.modules.foundations.vip.render.VipPrivilegesRender;
   import game.ui.vipModule.render.VipGiftRenderUI;
   import nslm2.modules.foundations.vip.render.VipGiftRender;
   import game.ui.miniMaps.MiniMapHintRenderUI;
   import nslm2.modules.foundations.miniMaps.MiniMapHintRender;
   import game.ui.fundModule.render.FundRewardRenderUI;
   import nslm2.modules.foundations.fund.render.FundRewardRender;
   import game.ui.fundModule.render.FundPelopleRenderUI;
   import nslm2.modules.foundations.fund.render.FundPelopleRender;
   import game.ui.commons.comps.others.EquipStarRenderUI;
   import nslm2.modules.cultivates.equipGrows.upStars.EquipStarRender;
   import game.ui.equipGrows.upStars.EquipUpStarMannalRenderUI;
   import nslm2.modules.cultivates.equipGrows.upStars.EquipUpStarMannalRender;
   import game.ui.playerTitle.render.PlayerTitlesRenderUI;
   import nslm2.modules.funnies.playerTitles.render.PlayerTitlesRender;
   import game.ui.playerTitle.render.PlayerTitleListRenderUI;
   import nslm2.modules.funnies.playerTitles.render.PlayerTitleListRender;
   import game.ui.playerTitle.render.PlayerTitlePropRenderUI;
   import nslm2.modules.funnies.playerTitles.render.PlayerTitlePropRender;
   import game.ui.TencentModule.render.TencentTitleRenderUI;
   import nslm2.modules.funnies.tencent.render.TencentTitleRender;
   import game.ui.TencentModule.render.TencentVipRewardRenderUI;
   import nslm2.modules.funnies.tencent.render.TencentVipRewardRender;
   import game.ui.TencentModule.render.TencentVipRightsRenderUI;
   import nslm2.modules.funnies.tencent.render.TencentVipRightsRender;
   import game.ui.TencentModule.render.TencentVipLvlUpGiftRenderUI;
   import nslm2.modules.funnies.tencent.render.TencentVipLvlUpGiftRender;
   import game.ui.qihooModule.render.QihooLvlUpGiftRenderUI;
   import nslm2.modules.funnies.qihoo.render.QihooLvlUpGiftRender;
   import game.ui.sevenDayModule.view.DayGiftRenderUI;
   import nslm2.modules.foundations.sevenDays.view.DayGiftRender;
   import game.ui.sevenDayModule.view.DayRenderUI;
   import nslm2.modules.foundations.sevenDays.view.DayRender;
   import game.ui.sevenDayModule.view.SevenDaysTaskRenderUI;
   import nslm2.modules.foundations.sevenDays.view.SevenDaysTaskRender;
   import game.ui.settingModule.view.FuncSettingListRenderUI;
   import nslm2.modules.foundations.setting.view.FuncSettingListRender;
   import game.ui.mainToolBar.BottomIconRenderUI;
   import nslm2.modules.foundations.mainToolBar.BottomIconRender;
   import game.ui.roleInfos.RoleSelectRenderUI;
   import nslm2.modules.roleInfos.RoleSelectRender;
   import game.ui.roleInfos.equipPanels.RolePropSuitRenderUI;
   import nslm2.modules.roleInfos.equipPanels.RolePropSuitRender;
   import game.ui.roleInfos.equipPanels.RoleEquipRenderUI;
   import nslm2.modules.roleInfos.equipPanels.RoleEquipRender;
   import game.ui.roleInfos.phaseUps.PhashUpPropRenderUI;
   import nslm2.modules.roleInfos.phaseUps.PhashUpPropRender;
   import game.ui.equipGrows.equipSelectors.EquipSelectorRenderUI;
   import nslm2.modules.cultivates.equipGrows.comp.EquipSelectorRender;
   import game.ui.roleInfos.equipPanels.RoleMengYuePropRenderUI;
   import nslm2.modules.roleInfos.equipPanels.RoleMengYuePropRender;
   import game.ui.roleInfos.equipPanels.RoleSelectEquipRenderUI;
   import nslm2.modules.roleInfos.equipPanels.RoleSelectEquipRender;
   import game.ui.mainToolBar.BottomIconBarUI;
   import nslm2.modules.foundations.mainToolBar.BottomIconBar;
   import game.ui.mainToolBar.BottomIconBarTopRightUI;
   import nslm2.modules.foundations.mainToolBar.BottomIconBarTopRight;
   import game.ui.mainToolBar.BottomIconBarVerticalUI;
   import nslm2.modules.foundations.mainToolBar.BottomIconBarVertical;
   import game.ui.mainToolBar.BottomIconRenderBigUI;
   import nslm2.modules.foundations.mainToolBar.BottomIconRenderBig;
   import game.ui.mainCitys.ResDgSelectBossListUI;
   import nslm2.modules.scenes.mainCitys.ResDgSelectBossList;
   import game.ui.mainCitys.ResDgSelectBossListRenderUI;
   import nslm2.modules.scenes.mainCitys.ResDgSelectBossListRender;
   import game.ui.playerHeaders.PlayerMilitaryRenderUI;
   import nslm2.modules.foundations.playerHeaders.PlayerMilitaryRender;
   import game.ui.resourceDungeonModule.RDProcessRenderUI;
   import nslm2.modules.battles.resourceDungeons.ResDgProcessRender;
   import game.ui.heroShowModule.HeroShowRenderUI;
   import nslm2.modules.cultivates.heroBag.HeroShowRender;
   import game.ui.roleInfos.equipPanels.RoleDetailPropPanelUI;
   import nslm2.modules.roleInfos.equipPanels.RoleDetailPropPanel;
   import game.ui.treasures.render.RuneHoleListRenderUI;
   import nslm2.modules.cultivates.treasure.view.render.RuneHoleListRender;
   import game.ui.tooltipModules.comps.ToolTipRuneRenderUI;
   import nslm2.modules.footstones.tooltipsModules.uis.comps.ToolTipRuneRender;
   import game.ui.tooltipModules.comps.TooltipGodhoodRenderUI;
   import nslm2.modules.footstones.tooltipsModules.uis.comps.TooltipGodhoodRender;
   import game.ui.treasures.render.OpenHoleCostRenderUI;
   import nslm2.modules.cultivates.treasure.view.render.OpenHoleCostRender;
   import game.ui.dailyTaskModules.DailyTaskListRenderUI;
   import nslm2.modules.foundations.dailyTask.render.DailyTaskListRender;
   import game.ui.dailyTaskModules.ResBackRenderUI;
   import nslm2.modules.foundations.dailyTask.render.ResBackRender;
   import game.ui.treasures.render.RuneListBigRenderUI;
   import nslm2.modules.cultivates.treasure.view.render.RuneListBigRender;
   import game.ui.resourceDg.ResBossRenderUI;
   import nslm2.modules.scenes.mainCitys.ResBossRender;
   import game.ui.resourceDg.ResCellUI;
   import nslm2.modules.scenes.mainCitys.ResCell;
   import game.ui.roleInfos.tupos.RoleTupoNeedRenderUI;
   import nslm2.modules.roleInfos.tupos.RoleTupoNeedRender;
   import game.ui.roleInfos.tupos.RoleTupoConfirmRenderUI;
   import nslm2.modules.roleInfos.tupos.RoleTupoConfirmRender;
   import game.ui.roleInfos.awake.render.RoleAwakeNeedRenderUI;
   import nslm2.modules.roleInfos.awake.render.RoleAwakeNeedRender;
   import game.ui.roleInfos.awake.render.RoleAwakeEquipPropRenderUI;
   import nslm2.modules.roleInfos.awake.render.RoleAwakeEquipPropRender;
   import game.ui.roleInfos.tupos.GodhoodRenderUI;
   import nslm2.modules.roleInfos.tupos.GodhoodRender;
   import game.ui.mallModule.render.MallListItemRenderUI;
   import nslm2.modules.foundations.mall.view.render.MallListItemRender;
   import game.ui.roleInfos.tupos.TupoTujianRenderUI;
   import nslm2.modules.roleInfos.tupos.TupoTujianRender;
   import game.ui.signInModules.SignInRenderUI;
   import nslm2.modules.foundations.signIn.SignInRender;
   import game.ui.signInModules.FSignInRenderUI;
   import nslm2.modules.foundations.signIn.FSignInRender;
   import game.ui.commons.icons.WealthRenderS11UI;
   import nslm2.modules.foundations.signIn.WealthRenderS11;
   import game.ui.commons.comps.others.TreasureBoxBaseRenderUI;
   import nslm2.common.ui.components.comps2d.others.TreasureBoxBaseRender;
   import game.ui.equipGrows.equipSelectors.EquipSelectHeroRenderUI;
   import nslm2.modules.cultivates.equipGrows.comp.EquipSelectHeroRender;
   import game.ui.recycleModules.render.RecycleItemRenderUI;
   import nslm2.modules.foundations.recycle.view.render.RecycleItemRender;
   import game.ui.recycleModules.render.RecSelectHeroRenderUI;
   import nslm2.modules.foundations.recycle.view.render.RecSelectHeroRender;
   import game.ui.recycleModules.render.RecSelectEquipRenderUI;
   import nslm2.modules.foundations.recycle.view.render.RecSelectEquipRender;
   import game.ui.recycleModules.render.RecGotItemRenderUI;
   import nslm2.modules.foundations.recycle.view.render.RecGotItemRender;
   import game.ui.recycleModules.render.RecSelectRebornHeroRenderUI;
   import nslm2.modules.foundations.recycle.view.render.RecSelectRebornHeroRender;
   import game.ui.recycleModules.render.RecSelectRebornTreasureRenderUI;
   import nslm2.modules.foundations.recycle.view.render.RecSelectRebornTreasureRender;
   import game.ui.recycleModules.render.RecSelectRebornEquipRenderUI;
   import nslm2.modules.foundations.recycle.view.render.RecSelectRebornEquipRender;
   import game.ui.commons.comps.others.RecycleAlertRenderUI;
   import nslm2.modules.foundations.recycle.view.render.RecycleAlertRender;
   import game.ui.roleTeam.render.TeamHeroListRenderUI;
   import nslm2.modules.cultivates.roleTeam.view.render.TeamHeroListRender;
   import game.ui.roleTeam.render.SelectTeamHeroRenderUI;
   import nslm2.modules.cultivates.roleTeam.view.render.SelectTeamHeroRender;
   import game.ui.roleTeam.render.YuanJunHeroListRenderUI;
   import nslm2.modules.cultivates.roleTeam.view.render.YuanJunHeroListRender;
   import game.ui.roleTeam.render.YuanFenDetailRenderUI;
   import nslm2.modules.cultivates.roleTeam.view.render.YuanFenDetailRender;
   import game.ui.roleTeam.render.YuanFenItemRenderUI;
   import nslm2.modules.cultivates.roleTeam.view.render.YuanFenItemRender;
   import game.ui.roleTeam.render.YuanFenTxtRenderUI;
   import nslm2.modules.cultivates.roleTeam.view.render.YuanFenTxtListRender;
   import game.ui.roleTeam.render.SelectYuanJunHeroRenderUI;
   import nslm2.modules.cultivates.roleTeam.view.render.SelectYuanJunHeroRender;
   import game.ui.roleTeam.render.TeamRoleViewRenderUI;
   import nslm2.modules.cultivates.roleTeam.view.render.TeamRoleViewRender;
   import game.ui.tooltipModules.comps.NpcCarrerTypeRenderUI;
   import nslm2.modules.footstones.tooltipsModules.uis.comps.NpcCarrerTypeRender;
   import game.ui.tooltipModules.comps.NpcGroupRenderUI;
   import nslm2.modules.footstones.tooltipsModules.uis.comps.ToolTipNpcGroupRender;
   import game.ui.tooltipModules.comps.TooltipWealthListRenderUI;
   import nslm2.modules.footstones.tooltipsModules.uis.comps.TooltipWealthListRender;
   import game.ui.treasures.comp.TreasureSelectorRenderUI;
   import nslm2.modules.cultivates.treasure.view.render.TreasureSelectorRender;
   import game.ui.treasures.render.TreasureListRenderUI;
   import nslm2.modules.cultivates.treasure.view.render.TreasureListRender;
   import game.ui.treasures.render.SelectTreasureRenderUI;
   import nslm2.modules.cultivates.treasure.view.render.SelectTreasureRender;
   import game.ui.commons.props.RolePropBaseRenderS1UI;
   import morn.customs.components.RolePropBaseRenderS1;
   import game.ui.commons.props.RolePropBaseRenderS2UI;
   import morn.customs.components.RolePropBaseRenderS2;
   import game.ui.roleInfos.phaseUps.RolePropPhaseUpRenderS1UI;
   import nslm2.modules.roleInfos.phaseUps.RolePropPhaseUpRenderS1;
   import game.ui.roleInfos.phaseUps.RolePropPhaseUpRenderS2UI;
   import nslm2.modules.roleInfos.phaseUps.RolePropPhaseUpRenderS2;
   import game.ui.roleInfos.phaseUps.RolePropPhaseUpRenderS3UI;
   import nslm2.modules.roleInfos.phaseUps.RolePropPhaseUpRenderS3;
   import game.ui.roleInfos.phaseUps.RolePhaseUpSkillRenderUI;
   import nslm2.modules.roleInfos.phaseUps.RolePhaseUpSkillRender;
   import game.ui.roleInfos.phaseUps.RolePhaseUpTwoPropRenderUI;
   import nslm2.modules.roleInfos.phaseUps.RolePhaseUpTwoPropRender;
   import game.ui.roleTeam.render.EquipMasterEquipRenderUI;
   import nslm2.modules.cultivates.roleTeam.view.render.equipMaster.EquipMasterEquipRender;
   import game.ui.treasures.render.RuneRenderUI;
   import nslm2.modules.cultivates.treasure.view.render.RuneListRender;
   import game.ui.treasures.render.RunePorpRenderUI;
   import nslm2.modules.cultivates.treasure.view.render.RunePorpRender;
   import game.ui.noticeModules.NoticeContentRenderUI;
   import nslm2.modules.foundations.noticeModule.view.render.NoticeContentListRender;
   import game.ui.teamGuajiScenes.pvp.TreasurePieceListRenderUI;
   import nslm2.modules.funnies.teamGuajiScenes.pvp.pieceBag.TreasurePieceListRender;
   import game.ui.tooltipModules.comps.TooltipPropRenderS3UI;
   import nslm2.modules.footstones.tooltipsModules.uis.comps.TooltipPropRenderS3;
   import game.ui.treasures.render.RuneCategoryRenderUI;
   import nslm2.modules.cultivates.treasure.view.render.RuneCategoryRender;
   import game.ui.treasures.render.RuneBgListRenderUI;
   import nslm2.modules.cultivates.treasure.view.render.RuneBagListRender;
   import game.ui.treasures.runeBag.RuneComposeRenderUI;
   import nslm2.modules.cultivates.treasure.view.render.RuneComeposeRender;
   import game.ui.treasures.runeBag.RuneComposeRenderToUI;
   import nslm2.modules.cultivates.treasure.view.render.RuneComposeToRender;
   import game.ui.treasures.render.OptionListRenderUI;
   import nslm2.modules.cultivates.treasure.view.render.OpiontListerRender;
   import game.ui.fashionAcc.FashionAccMaterialRenderUI;
   import nslm2.modules.cultivates.fashionAcc.render.FashionAccMaterialRender;
   import game.ui.fashionAcc.FashionAccRenderUI;
   import nslm2.modules.cultivates.fashionAcc.render.FashionAccRender;
   import game.ui.fashionAcc.FashionAccSelectTitleRenderUI;
   import nslm2.modules.cultivates.fashionAcc.render.FashionAccSelectTitleRender;
   import game.ui.fashionAcc.FashionAccSkillRenderUI;
   import nslm2.modules.cultivates.fashionAcc.render.FashionAccSkillRender;
   import game.ui.shenYuans.ShenYuanMosnterTipUI;
   import nslm2.modules.scenes.shenYuans.comp.ShenYuanMonsterTip;
   import game.ui.shenYuans.ShenYuanHelpRenderUI;
   import nslm2.modules.scenes.shenYuans.comp.ShenYuanHelpRender;
   import game.ui.shenYuans.ShenYuanHelpHeadUI;
   import nslm2.modules.scenes.shenYuans.comp.ShenYuanHelpHeadRender;
   import game.ui.rankModules.RankListRenderUI;
   import nslm2.modules.foundations.ranks.comp.RankListRender;
   import game.ui.rankModules.RankNameRenderUI;
   import nslm2.modules.foundations.ranks.comp.RankNameRender;
   import game.ui.friendModules.mains.FriendListTileRenderUI;
   import nslm2.modules.foundations.friendModules.mains.FriendListTileRender;
   import game.ui.friendModules.mains.FriendPlayerRenderUI;
   import nslm2.modules.foundations.friendModules.mains.FriendPlayerRender;
   import game.ui.friendModules.mains.FriendSubListUI;
   import nslm2.modules.foundations.friendModules.mains.FriendSubList;
   import game.ui.friendModules.mains.FriendSubListRenderUI;
   import nslm2.modules.foundations.friendModules.mains.FriendSubListRender;
   import game.ui.friendModules.mains.FriendBlockListRenderUI;
   import nslm2.modules.foundations.friendModules.mains.FriendBlockListRender;
   import game.ui.friendModules.mains.FriendQuickSearchRenderUI;
   import nslm2.modules.foundations.friendModules.mains.FriendQuickSearchRender;
   import game.ui.friendModules.mains.FriendRecentlyListRenderUI;
   import nslm2.modules.foundations.friendModules.mains.FriendRecentlyListRender;
   import game.ui.friendModules.mains.FriendRecenltyListRender_PlayerUI;
   import nslm2.modules.foundations.friendModules.mains.FriendRecenltyListRender_Player;
   import game.ui.friendModules.searches.FriendRecommendRenderUI;
   import nslm2.modules.foundations.friendModules.searches.FriendRecommendRender;
   import game.ui.friendModules.searches.FriendApplyRenderUI;
   import nslm2.modules.foundations.friendModules.searches.FriendApplyRender;
   import game.ui.friendModules.activities.FriendGiftRenderUI;
   import nslm2.modules.foundations.friendModules.activities.FriendGiftRender;
   import game.ui.friendModules.activities.FriendLogRenderUI;
   import nslm2.modules.foundations.friendModules.activities.FriendLogRender;
   import game.ui.MailModules.MailListRenderUI;
   import nslm2.modules.foundations.mail.MailListRender;
   import game.ui.MailModules.MailRewardRenderUI;
   import nslm2.modules.foundations.mail.MailRewardRender;
   import game.ui.MailModules.MailFriendRenderUI;
   import nslm2.modules.foundations.mail.MailFriendRender;
   import game.ui.heroCompare.render.HCHeroHeadRenderUI;
   import nslm2.modules.cultivates.otherRoleInfos.heroCompare.HCHeroHeadRender;
   import game.ui.heroCompare.render.HCHeroInfoRenderUI;
   import nslm2.modules.cultivates.otherRoleInfos.heroCompare.HCHeroInfoRender;
   import game.ui.heroCompare.render.HCHeroListRenderUI;
   import nslm2.modules.cultivates.otherRoleInfos.heroCompare.HCHeroListRender;
   import game.ui.heroCompare.render.HCHeroSubInfoRenderUI;
   import nslm2.modules.cultivates.otherRoleInfos.heroCompare.HCHeroSubInfoRender;
   import game.ui.heroCompare.render.HCDescRenderUI;
   import nslm2.modules.cultivates.otherRoleInfos.heroCompare.HCDescRender;
   import game.ui.heroCompare.render.HCCellRenderUI;
   import nslm2.modules.cultivates.otherRoleInfos.heroCompare.HCCellRender;
   import game.ui.skinModule.render.SkinListRenderUI;
   import nslm2.modules.cultivates.skin.render.SkinListSubRender;
   import game.ui.skinModule.render.SkinListSubRenderUI;
   import game.ui.skinModule.render.SkinBookSuitRenderUI;
   import nslm2.modules.cultivates.skin.render.SkinBookSuitRender;
   import game.ui.skinModule.render.SkinBookTitleRenderUI;
   import nslm2.modules.cultivates.skin.render.SkinBookTitleRender;
   import game.ui.skinModule.SkinBookPageBarUI;
   import nslm2.modules.cultivates.skin.SkinBookPageBar;
   import game.ui.skinModule.render.SkinRenderUI;
   import nslm2.modules.cultivates.skin.render.SkinRender;
   import game.ui.skinModule.render.SkinEquipRenderUI;
   import nslm2.modules.cultivates.skin.render.SkinEquipRender;
   import game.ui.fashionModules.FashionListRenderUI;
   import nslm2.modules.cultivates.fashion.FashionListSubRender;
   import game.ui.fashionModules.FashionSuitSkillRenderUI;
   import nslm2.modules.cultivates.fashion.FashionSuitSkillRender;
   import game.ui.fashionModules.FashionEquipRenderUI;
   import nslm2.modules.cultivates.fashion.FashionEquipRender;
   import game.ui.fashionModules.FashionListSubRenderUI;
   import game.ui.fashionModules.FashionRenderUI;
   import nslm2.modules.cultivates.fashion.FashionRender;
   import game.ui.fashionModules.FashionPropTwoRenderUI;
   import nslm2.modules.cultivates.fashion.FashionPropTwoRender;
   import game.ui.fightPlayers.RightHeaderUI;
   import nslm2.modules.battles.battle.RightHeader;
   import game.ui.statistic.LeftHeadUI;
   import nslm2.modules.battles.battleStatistic.BSLeftRender;
   import game.ui.statistic.RightHeadUI;
   import nslm2.modules.battles.battleStatistic.BSRightRender;
   import game.ui.battleResults.BattleDropsNameRenderUI;
   import nslm2.modules.battles.battleResults.BattleDropsNameRender;
   import game.ui.battleResults.BattleBtnsRenderUI;
   import nslm2.modules.battles.battleResults.render.BattleBtnsRender;
   import game.ui.recycleModules.render.RecWealthRenderUI;
   import nslm2.modules.foundations.recycle.view.render.RecResourceRender;
   import game.ui.recycleModules.petReborn.RecSelectRebornPetRenderUI;
   import nslm2.modules.foundations.recycle.view.render.RecSelectRebornPetRender;
   import game.ui.commons.icons.WealthRenderS7UI;
   import nslm2.common.ui.components.comps2d.WealthRenderS7;
   import game.ui.commons.icons.LotteryRenderS5UI;
   import nslm2.common.ui.components.comps2d.LotteryRenderS5;
   import game.ui.commons.icons.SkillRenderS8UI;
   import nslm2.common.ui.components.comps2d.SkillRenderS8;
   import game.ui.npcFuncLists.NpcFuncListRenderUI;
   import nslm2.modules.funnies.npcFuncLists.NpcFuncListRender;
   import game.ui.npcFuncLists.NpcFuncListRenderFakeUI;
   import game.ui.npcFuncLists.NpcFuncListPlayerIconUI;
   import nslm2.modules.funnies.npcFuncLists.NpcFuncListPlayerIcon;
   import game.ui.lvlUpModules.FunctionListRenderUI;
   import nslm2.modules.footstones.roleLvlUpModule.view.FunctionListRender;
   import game.ui.lvlUpModules.PropListRenderUI;
   import nslm2.modules.footstones.roleLvlUpModule.view.PropListRender;
   import game.ui.commons.icons.HeroRenderS1UI;
   import nslm2.common.ui.components.comps2d.HeroRenderS1;
   import game.ui.battleResults.BattleLossRenderUI;
   import nslm2.modules.battles.battleResults.battleLoss.BattleLossRender;
   import game.ui.commons.comps.others.RuleDescriptionUI;
   import nslm2.common.ui.components.comps2d.RuleDesComponent;
   import game.ui.pkCrossSer.PKCrossTopUI;
   import nslm2.modules.funnies.pkCrossSer.PKCrossTop;
   import game.ui.pkCrossSer.PKCrossRankRenderUI;
   import nslm2.modules.funnies.pkCrossSer.PKCrossRankRender;
   import game.ui.playerHeaders.CardInfoRenderUI;
   import nslm2.modules.foundations.playerHeaders.CardInfoRender;
   import game.ui.abilityRankModule.render.AbilityRankListRenderUI;
   import nslm2.modules.funnies.abilityRankModule.render.AbilityRankListRender;
   import game.ui.abilityRankModule.render.AbilityRewardRenderUI;
   import nslm2.modules.funnies.abilityRankModule.render.RewardWealthRender;
   import game.ui.teamPKCS.finalMatch.TPKCHalfRenderUI;
   import nslm2.modules.funnies.teamPKCS.finalMatch.TPKCHalfRender;
   import game.ui.teamPKCS.finalMatch.TPKCGambleLeftRenderUI;
   import nslm2.modules.funnies.teamPKCS.finalMatch.TPKCGambleLeftRender;
   import game.ui.teamPKCS.finalMatch.TPKCGambleRightRenderUI;
   import nslm2.modules.funnies.teamPKCS.finalMatch.TPKCGambleRightRender;
   import game.ui.angelFundModule.render.AngelFundTitleRenderUI;
   import nslm2.modules.foundations.angelFund.render.AngelFundTitleRender;
   import game.ui.secretExplore.SEfaceUI;
   import nslm2.modules.funnies.secretExplore.SEface;
   import game.ui.newYears.olmpic2016.OlmpicSelCountryRenderUI;
   import nslm2.modules.funnies.newYears.olmpic2016.OlmpicSelCountryRender;
   import nslm2.inits.regRuntimes.RegRuntime_LotteryHero;
   import nslm2.inits.regRuntimes.RegRunTime_TeamGuaji;
   import nslm2.inits.regRuntimes.RegRuntime_Commons;
   import nslm2.inits.regRuntimes.RegRuntime_Arena;
   import nslm2.inits.regRuntimes.RegRuntime_Horse;
   import nslm2.inits.regRuntimes.RegRuntime_Shop;
   import nslm2.inits.regRuntimes.RegRuntime_Military;
   import nslm2.inits.regRuntimes.RegRuntime_team;
   import nslm2.inits.regRuntimes.RegRuntime_Chapter;
   import nslm2.inits.regRuntimes.RuntimeChampionship;
   import nslm2.inits.regRuntimes.RegRuntime_Guild;
   import nslm2.inits.regRuntimes.RegRuntime_Mall;
   import nslm2.inits.regRuntimes.RegRunTime_Tools;
   import nslm2.inits.regRuntimes.RegRuntime_Activities;
   import nslm2.inits.regRuntimes.RegRuntime_RecommendHero;
   import nslm2.inits.regRuntimes.RegRuntime_Battlefields;
   import nslm2.inits.regRuntimes.RegRuntime_FamilyBoss;
   import nslm2.inits.regRuntimes.RegRuntime_Vip;
   import nslm2.inits.regRuntimes.RegRuneTime_Auction;
   import nslm2.inits.regRuntimes.RegRuntime_RenZhengs;
   import nslm2.inits.regRuntimes.RegRuntim_QQ;
   import nslm2.inits.regRuntimes.RegRuntime_NewYear;
   import nslm2.inits.regRuntimes.RegRuneTime_HeroAwakenRoad;
   import nslm2.inits.regRuntimes.RegRuntime_XunLeiGift;
   import nslm2.inits.regRuntimes.RegRuntime_Tencent;
   import nslm2.inits.regRuntimes.RegRuntime_Assistant;
   import nslm2.inits.regRuntimes.RegRuntime_FaceBook;
   import nslm2.inits.regRuntimes.RegRunTime_WorldBoss;
   import nslm2.inits.regRuntimes.RegRunTime_Groupon;
   import nslm2.inits.regRuntimes.RegRunTime_Dial;
   import nslm2.inits.regRuntimes.RegRunTime_Day38;
   import nslm2.inits.regRuntimes.RegRuntime_LuckTree;
   import nslm2.inits.regRuntimes.RegRunTime_Pet;
   import nslm2.inits.regRuntimes.RegRunTime_HeroChoose;
   import nslm2.inits.regRuntimes.RegRuntime_Recycle;
   import nslm2.inits.regRuntimes.RegRuntime_busyAcitivitys;
   import nslm2.inits.regRuntimes.RegRuntime_PeakSports;
   
   public class RegRuntimeClassTask extends TaskBase
   {
       
      
      public function RegRuntimeClassTask()
      {
         super();
      }
      
      override public function exec() : void
      {
         View.runtimeClassMap[NewerGuideCommonRenderUI] = NewerGuideArrow;
         View.runtimeClassMap[NewerGuideSkipUI] = NewerGuideSkip;
         View.runtimeClassMap[NewerGuideNPCSayUI] = NewerGuideNPCSay;
         View.runtimeClassMap[RedPointNumUI] = RedPointNum;
         View.runtimeClassMap[RedPointUI] = RedPoint;
         View.runtimeClassMap[BtnOkUI] = BtnOK;
         View.runtimeClassMap[BtnCancelUI] = BtnCancel;
         View.runtimeClassMap[TaskAlertRenderUI] = TaskAlertRender;
         View.runtimeClassMap[TaskAlertRenderS3UI] = TaskAlertRenderS3;
         View.runtimeClassMap[MiniMapBtnUI] = MiniMapBtn;
         View.runtimeClassMap[ChangeLineUI] = ChangeLine;
         View.runtimeClassMap[MiniMapLineRenderUI] = MiniMapLineRender;
         View.runtimeClassMap[FightValueBoxUI] = FightValueBox;
         View.runtimeClassMap[FightValueBoxS2UI] = FightValueBoxS2;
         View.runtimeClassMap[FightValueBoxS4UI] = FightValueBoxS4;
         View.runtimeClassMap[ClickToNextUI] = ClickToNext;
         View.runtimeClassMap[ClickToNextButtonUI] = ClickToNextButton;
         View.runtimeClassMap[ClickToNextButtonTimeUI] = ClickToNextButtonTime;
         View.runtimeClassMap[BagItemRenderUI] = BagItemRender;
         View.runtimeClassMap[SellBatchItemRenderUI] = SellBatchItemRender;
         View.runtimeClassMap[UseGiftRenderUI] = UseGiftRender;
         View.runtimeClassMap[GetGiftRenderUI] = GetGiftRender;
         View.runtimeClassMap[SellBatchItemWealthRenderUI] = SellBatchItemWealthRender;
         View.runtimeClassMap[EquipComposeRenderToUI] = EquipComposeRenderTo;
         View.runtimeClassMap[TestAccordionTitleRenderUI] = TestAccordionTitleRender;
         View.runtimeClassMap[TestAccordionContentRenderUI] = TestAccordionContentRender;
         View.runtimeClassMap[LoadingSceneUI] = LoadingScene;
         View.runtimeClassMap[LoadingPopUI] = LoadingPop;
         View.runtimeClassMap[TooltipTxtUI] = TooltipTxt;
         View.runtimeClassMap[PageBarS1UI] = PageBarS1;
         View.runtimeClassMap[PageBarS2UI] = PageBarS2;
         View.runtimeClassMap[PageBarS3UI] = PageBarS3;
         View.runtimeClassMap[PageBarS4UI] = PageBarS4;
         View.runtimeClassMap[NumBarS1UI] = NumBarS1;
         View.runtimeClassMap[BtnRenderUI] = BtnRender;
         View.runtimeClassMap[TupoClipRenderUI] = TupoClipRender;
         View.runtimeClassMap[PlayerTitleRenderUI] = PlayerTitleRender;
         View.runtimeClassMap[ResGetPointListRenderUI] = ResGetPointListRender;
         View.runtimeClassMap[ResGetPointResRenderUI] = ResGetPointResRender;
         View.runtimeClassMap[RoleSelectListPanelUI] = RoleSelectListPanel;
         View.runtimeClassMap[RoleBaoWuRenderUI] = RoleBaoWuRender;
         View.runtimeClassMap[RoleDetailPropRenderUI] = RoleDetailPropListRender;
         View.runtimeClassMap[YuanFenRenderUI] = YuanFengListRender;
         View.runtimeClassMap[BasePropRenderUI] = RoleBasePropRender;
         View.runtimeClassMap[SkillShowRenderUI] = PhaseUpSkillShowRender;
         View.runtimeClassMap[ShenjieTujianListRenderUI] = RoleShenjieTujianRender;
         View.runtimeClassMap[SkillRenderSmallUI] = SkillRenderSmall;
         View.runtimeClassMap[DetailYuanfenInfoRenderUI] = DetailYuanFenRender;
         View.runtimeClassMap[TianfuInfoRenderUI] = TianfuRender;
         View.runtimeClassMap[OtherRoleEquipRenderUI] = OtherRoleEquipRender;
         View.runtimeClassMap[OtherRoleYuanJunRenderUI] = OtherRoleYuanJunRender;
         View.runtimeClassMap[OtherRoleListRenderUI] = OtherRoleListRender;
         View.runtimeClassMap[OtherRoleListPetRenderUI] = OtherRoleListPetRender;
         View.runtimeClassMap[ChatSendBoxUI] = ChatSendBox;
         View.runtimeClassMap[ChatFaceSelectPanelUI] = ChatFaceSelectPanel;
         View.runtimeClassMap[ChatBtnChannelRenderUI] = ChatBtnChannelRender;
         View.runtimeClassMap[ChatHistoryUI] = ChatHistory;
         View.runtimeClassMap[ChatHistoryPanelS1UI] = ChatHistoryPanelS1;
         View.runtimeClassMap[ChatHistoryPanelS2UI] = ChatHistoryPanelS2;
         View.runtimeClassMap[ChatHistoryPanelS3UI] = ChatHistoryPanelS3;
         View.runtimeClassMap[ChatHistoryPanelLocalUI] = ChatHistoryPanelLocal;
         View.runtimeClassMap[ChatHistoryHeaderIconUI] = ChatHistoryHeaderIcon;
         View.runtimeClassMap[PrivChatRoleListUI] = PrivChatRoleList;
         View.runtimeClassMap[PrivChatRoleListRenderUI] = PrivChatRoleListRender;
         View.runtimeClassMap[PrivChatPlayerRenderUI] = PrivChatPlayerRender;
         View.runtimeClassMap[PrivChatRoleListRender_playerUI] = PrivChatRoleListRender_player;
         View.runtimeClassMap[PrivChatHistoryUI] = PrivChatHistory;
         View.runtimeClassMap[PrivChatSendUI] = PrivChatSend;
         View.runtimeClassMap[PlayerHeaderStaminaBarUI] = PlayerHeaderStaminaBar;
         View.runtimeClassMap[ExpBarUI] = ExpBar;
         View.runtimeClassMap[SkillChangeRenderUI] = SkillChangeRender;
         View.runtimeClassMap[SkillKindRenderUI] = SkillKindRender;
         View.runtimeClassMap[PlayerHeaderWealthRenderUI] = PlayerHeaderWealthRender;
         View.runtimeClassMap[PlayerHeaderWealthRenderSmallUI] = PlayerHeaderWealthRenderSmall;
         View.runtimeClassMap[PropRenderUI] = PropRender;
         View.runtimeClassMap[RandomPropRenderUI] = RandomPorpRender;
         View.runtimeClassMap[RoleAwakePropRenderUI] = RoleAwakePropRender;
         View.runtimeClassMap[ValentineSalesRenderUI] = ValentineSalesRender;
         View.runtimeClassMap[LanternSalesRenderUI] = LanternSalesRender;
         View.runtimeClassMap[SevenDaysSaleRenderUI] = FourteenDaysSaleRender;
         View.runtimeClassMap[SalesPelopleNumRenderUI] = SalesPelopleNumRender;
         View.runtimeClassMap[SalesItemRenderUI] = SalesItemRender;
         View.runtimeClassMap[SalesBenefitRenderUI] = SalesBenefitRender;
         View.runtimeClassMap[GameHelpTitleRenderUI] = GameHelpTitleRender;
         View.runtimeClassMap[GameHelpRenderUI] = GameHelpRender;
         View.runtimeClassMap[ChargeRenderUI] = ChargeRender;
         View.runtimeClassMap[VipPrivilegeRenderUI] = VipPrivilegeRender;
         View.runtimeClassMap[VipPrivilegesRenderUI] = VipPrivilegesRender;
         View.runtimeClassMap[VipGiftRenderUI] = VipGiftRender;
         View.runtimeClassMap[MiniMapHintRenderUI] = MiniMapHintRender;
         View.runtimeClassMap[FundRewardRenderUI] = FundRewardRender;
         View.runtimeClassMap[FundPelopleRenderUI] = FundPelopleRender;
         View.runtimeClassMap[EquipStarRenderUI] = EquipStarRender;
         View.runtimeClassMap[EquipUpStarMannalRenderUI] = EquipUpStarMannalRender;
         View.runtimeClassMap[PlayerTitlesRenderUI] = PlayerTitlesRender;
         View.runtimeClassMap[PlayerTitleListRenderUI] = PlayerTitleListRender;
         View.runtimeClassMap[PlayerTitlePropRenderUI] = PlayerTitlePropRender;
         View.runtimeClassMap[TencentTitleRenderUI] = TencentTitleRender;
         View.runtimeClassMap[TencentVipRewardRenderUI] = TencentVipRewardRender;
         View.runtimeClassMap[TencentVipRightsRenderUI] = TencentVipRightsRender;
         View.runtimeClassMap[TencentVipLvlUpGiftRenderUI] = TencentVipLvlUpGiftRender;
         View.runtimeClassMap[QihooLvlUpGiftRenderUI] = QihooLvlUpGiftRender;
         View.runtimeClassMap[DayGiftRenderUI] = DayGiftRender;
         View.runtimeClassMap[DayRenderUI] = DayRender;
         View.runtimeClassMap[SevenDaysTaskRenderUI] = SevenDaysTaskRender;
         View.runtimeClassMap[DayGiftRenderUI] = DayGiftRender;
         View.runtimeClassMap[FuncSettingListRenderUI] = FuncSettingListRender;
         View.runtimeClassMap[DayRenderUI] = DayRender;
         View.runtimeClassMap[BottomIconRenderUI] = BottomIconRender;
         View.runtimeClassMap[RoleSelectRenderUI] = RoleSelectRender;
         View.runtimeClassMap[RolePropSuitRenderUI] = RolePropSuitRender;
         View.runtimeClassMap[RoleEquipRenderUI] = RoleEquipRender;
         View.runtimeClassMap[PhashUpPropRenderUI] = PhashUpPropRender;
         View.runtimeClassMap[EquipSelectorRenderUI] = EquipSelectorRender;
         View.runtimeClassMap[RoleMengYuePropRenderUI] = RoleMengYuePropRender;
         View.runtimeClassMap[RoleSelectEquipRenderUI] = RoleSelectEquipRender;
         View.runtimeClassMap[BottomIconBarUI] = BottomIconBar;
         View.runtimeClassMap[BottomIconBarTopRightUI] = BottomIconBarTopRight;
         View.runtimeClassMap[BottomIconBarVerticalUI] = BottomIconBarVertical;
         View.runtimeClassMap[BottomIconRenderBigUI] = BottomIconRenderBig;
         View.runtimeClassMap[ResDgSelectBossListUI] = ResDgSelectBossList;
         View.runtimeClassMap[ResDgSelectBossListRenderUI] = ResDgSelectBossListRender;
         View.runtimeClassMap[PlayerMilitaryRenderUI] = PlayerMilitaryRender;
         View.runtimeClassMap[RDProcessRenderUI] = ResDgProcessRender;
         View.runtimeClassMap[HeroShowRenderUI] = HeroShowRender;
         View.runtimeClassMap[RoleDetailPropPanelUI] = RoleDetailPropPanel;
         View.runtimeClassMap[RuneHoleListRenderUI] = RuneHoleListRender;
         View.runtimeClassMap[ToolTipRuneRenderUI] = ToolTipRuneRender;
         View.runtimeClassMap[TooltipGodhoodRenderUI] = TooltipGodhoodRender;
         View.runtimeClassMap[OpenHoleCostRenderUI] = OpenHoleCostRender;
         View.runtimeClassMap[DailyTaskListRenderUI] = DailyTaskListRender;
         View.runtimeClassMap[ResBackRenderUI] = ResBackRender;
         View.runtimeClassMap[RuneListBigRenderUI] = RuneListBigRender;
         View.runtimeClassMap[ResBossRenderUI] = ResBossRender;
         View.runtimeClassMap[ResCellUI] = ResCell;
         View.runtimeClassMap[RoleTupoNeedRenderUI] = RoleTupoNeedRender;
         View.runtimeClassMap[RoleTupoConfirmRenderUI] = RoleTupoConfirmRender;
         View.runtimeClassMap[RoleAwakeNeedRenderUI] = RoleAwakeNeedRender;
         View.runtimeClassMap[RoleAwakeEquipPropRenderUI] = RoleAwakeEquipPropRender;
         View.runtimeClassMap[GodhoodRenderUI] = GodhoodRender;
         View.runtimeClassMap[MallListItemRenderUI] = MallListItemRender;
         View.runtimeClassMap[TupoTujianRenderUI] = TupoTujianRender;
         View.runtimeClassMap[SignInRenderUI] = SignInRender;
         View.runtimeClassMap[FSignInRenderUI] = FSignInRender;
         View.runtimeClassMap[WealthRenderS11UI] = WealthRenderS11;
         View.runtimeClassMap[TreasureBoxBaseRenderUI] = TreasureBoxBaseRender;
         View.runtimeClassMap[EquipSelectHeroRenderUI] = EquipSelectHeroRender;
         View.runtimeClassMap[RecycleItemRenderUI] = RecycleItemRender;
         View.runtimeClassMap[RecSelectHeroRenderUI] = RecSelectHeroRender;
         View.runtimeClassMap[RecSelectEquipRenderUI] = RecSelectEquipRender;
         View.runtimeClassMap[RecGotItemRenderUI] = RecGotItemRender;
         View.runtimeClassMap[RecSelectRebornHeroRenderUI] = RecSelectRebornHeroRender;
         View.runtimeClassMap[RecSelectRebornTreasureRenderUI] = RecSelectRebornTreasureRender;
         View.runtimeClassMap[RecSelectRebornEquipRenderUI] = RecSelectRebornEquipRender;
         View.runtimeClassMap[RecycleAlertRenderUI] = RecycleAlertRender;
         View.runtimeClassMap[TeamHeroListRenderUI] = TeamHeroListRender;
         View.runtimeClassMap[SelectTeamHeroRenderUI] = SelectTeamHeroRender;
         View.runtimeClassMap[YuanJunHeroListRenderUI] = YuanJunHeroListRender;
         View.runtimeClassMap[YuanFenDetailRenderUI] = YuanFenDetailRender;
         View.runtimeClassMap[YuanFenItemRenderUI] = YuanFenItemRender;
         View.runtimeClassMap[YuanFenItemRenderUI] = YuanFenItemRender;
         View.runtimeClassMap[YuanFenTxtRenderUI] = YuanFenTxtListRender;
         View.runtimeClassMap[SelectYuanJunHeroRenderUI] = SelectYuanJunHeroRender;
         View.runtimeClassMap[TeamRoleViewRenderUI] = TeamRoleViewRender;
         View.runtimeClassMap[NpcCarrerTypeRenderUI] = NpcCarrerTypeRender;
         View.runtimeClassMap[NpcGroupRenderUI] = ToolTipNpcGroupRender;
         View.runtimeClassMap[TooltipWealthListRenderUI] = TooltipWealthListRender;
         View.runtimeClassMap[TreasureSelectorRenderUI] = TreasureSelectorRender;
         View.runtimeClassMap[TreasureListRenderUI] = TreasureListRender;
         View.runtimeClassMap[SelectTreasureRenderUI] = SelectTreasureRender;
         View.runtimeClassMap[RolePropBaseRenderS1UI] = RolePropBaseRenderS1;
         View.runtimeClassMap[RolePropBaseRenderS2UI] = RolePropBaseRenderS2;
         View.runtimeClassMap[RolePropPhaseUpRenderS1UI] = RolePropPhaseUpRenderS1;
         View.runtimeClassMap[RolePropPhaseUpRenderS2UI] = RolePropPhaseUpRenderS2;
         View.runtimeClassMap[RolePropPhaseUpRenderS3UI] = RolePropPhaseUpRenderS3;
         View.runtimeClassMap[RolePhaseUpSkillRenderUI] = RolePhaseUpSkillRender;
         View.runtimeClassMap[RolePhaseUpTwoPropRenderUI] = RolePhaseUpTwoPropRender;
         View.runtimeClassMap[EquipMasterEquipRenderUI] = EquipMasterEquipRender;
         View.runtimeClassMap[RuneRenderUI] = RuneListRender;
         View.runtimeClassMap[RunePorpRenderUI] = RunePorpRender;
         View.runtimeClassMap[NoticeContentRenderUI] = NoticeContentListRender;
         View.runtimeClassMap[TreasurePieceListRenderUI] = TreasurePieceListRender;
         View.runtimeClassMap[TooltipPropRenderS3UI] = TooltipPropRenderS3;
         View.runtimeClassMap[RuneCategoryRenderUI] = RuneCategoryRender;
         View.runtimeClassMap[RuneBgListRenderUI] = RuneBagListRender;
         View.runtimeClassMap[RuneComposeRenderUI] = RuneComeposeRender;
         View.runtimeClassMap[RuneComposeRenderToUI] = RuneComposeToRender;
         View.runtimeClassMap[OptionListRenderUI] = OpiontListerRender;
         View.runtimeClassMap[FashionAccMaterialRenderUI] = FashionAccMaterialRender;
         View.runtimeClassMap[FashionAccRenderUI] = FashionAccRender;
         View.runtimeClassMap[FashionAccSelectTitleRenderUI] = FashionAccSelectTitleRender;
         View.runtimeClassMap[FashionAccSkillRenderUI] = FashionAccSkillRender;
         View.runtimeClassMap[ShenYuanMosnterTipUI] = ShenYuanMonsterTip;
         View.runtimeClassMap[ShenYuanHelpRenderUI] = ShenYuanHelpRender;
         View.runtimeClassMap[ShenYuanHelpHeadUI] = ShenYuanHelpHeadRender;
         View.runtimeClassMap[RankListRenderUI] = RankListRender;
         View.runtimeClassMap[RankNameRenderUI] = RankNameRender;
         View.runtimeClassMap[FriendListTileRenderUI] = FriendListTileRender;
         View.runtimeClassMap[FriendPlayerRenderUI] = FriendPlayerRender;
         View.runtimeClassMap[FriendSubListUI] = FriendSubList;
         View.runtimeClassMap[FriendSubListRenderUI] = FriendSubListRender;
         View.runtimeClassMap[FriendBlockListRenderUI] = FriendBlockListRender;
         View.runtimeClassMap[FriendQuickSearchRenderUI] = FriendQuickSearchRender;
         View.runtimeClassMap[FriendRecentlyListRenderUI] = FriendRecentlyListRender;
         View.runtimeClassMap[FriendRecenltyListRender_PlayerUI] = FriendRecenltyListRender_Player;
         View.runtimeClassMap[FriendRecommendRenderUI] = FriendRecommendRender;
         View.runtimeClassMap[FriendApplyRenderUI] = FriendApplyRender;
         View.runtimeClassMap[FriendGiftRenderUI] = FriendGiftRender;
         View.runtimeClassMap[FriendLogRenderUI] = FriendLogRender;
         View.runtimeClassMap[MailListRenderUI] = MailListRender;
         View.runtimeClassMap[MailRewardRenderUI] = MailRewardRender;
         View.runtimeClassMap[MailFriendRenderUI] = MailFriendRender;
         View.runtimeClassMap[HCHeroHeadRenderUI] = HCHeroHeadRender;
         View.runtimeClassMap[HCHeroInfoRenderUI] = HCHeroInfoRender;
         View.runtimeClassMap[HCHeroListRenderUI] = HCHeroListRender;
         View.runtimeClassMap[HCHeroSubInfoRenderUI] = HCHeroSubInfoRender;
         View.runtimeClassMap[HCDescRenderUI] = HCDescRender;
         View.runtimeClassMap[HCCellRenderUI] = HCCellRender;
         View.runtimeClassMap[SkinListRenderUI] = SkinListSubRender;
         View.runtimeClassMap[SkinListSubRenderUI] = SkinListSubRender;
         View.runtimeClassMap[SkinBookSuitRenderUI] = SkinBookSuitRender;
         View.runtimeClassMap[SkinBookTitleRenderUI] = SkinBookTitleRender;
         View.runtimeClassMap[SkinBookPageBarUI] = SkinBookPageBar;
         View.runtimeClassMap[SkinRenderUI] = SkinRender;
         View.runtimeClassMap[SkinEquipRenderUI] = SkinEquipRender;
         View.runtimeClassMap[FashionListRenderUI] = FashionListSubRender;
         View.runtimeClassMap[FashionSuitSkillRenderUI] = FashionSuitSkillRender;
         View.runtimeClassMap[FashionEquipRenderUI] = FashionEquipRender;
         View.runtimeClassMap[FashionListSubRenderUI] = FashionListSubRender;
         View.runtimeClassMap[FashionRenderUI] = FashionRender;
         View.runtimeClassMap[FashionPropTwoRenderUI] = FashionPropTwoRender;
         View.runtimeClassMap[RightHeaderUI] = RightHeader;
         View.runtimeClassMap[LeftHeadUI] = BSLeftRender;
         View.runtimeClassMap[RightHeadUI] = BSRightRender;
         View.runtimeClassMap[BattleDropsNameRenderUI] = BattleDropsNameRender;
         View.runtimeClassMap[BattleBtnsRenderUI] = BattleBtnsRender;
         View.runtimeClassMap[RecWealthRenderUI] = RecResourceRender;
         View.runtimeClassMap[RecSelectRebornPetRenderUI] = RecSelectRebornPetRender;
         View.runtimeClassMap[WealthRenderS7UI] = WealthRenderS7;
         View.runtimeClassMap[LotteryRenderS5UI] = LotteryRenderS5;
         View.runtimeClassMap[SkillRenderS8UI] = SkillRenderS8;
         View.runtimeClassMap[NpcFuncListRenderUI] = NpcFuncListRender;
         View.runtimeClassMap[NpcFuncListRenderFakeUI] = NpcFuncListRender;
         View.runtimeClassMap[NpcFuncListPlayerIconUI] = NpcFuncListPlayerIcon;
         View.runtimeClassMap[FunctionListRenderUI] = FunctionListRender;
         View.runtimeClassMap[PropListRenderUI] = PropListRender;
         View.runtimeClassMap[HeroRenderS1UI] = HeroRenderS1;
         View.runtimeClassMap[BattleLossRenderUI] = BattleLossRender;
         View.runtimeClassMap[RuleDescriptionUI] = RuleDesComponent;
         View.runtimeClassMap[PKCrossTopUI] = PKCrossTop;
         View.runtimeClassMap[PKCrossRankRenderUI] = PKCrossRankRender;
         View.runtimeClassMap[CardInfoRenderUI] = CardInfoRender;
         View.runtimeClassMap[AbilityRankListRenderUI] = AbilityRankListRender;
         View.runtimeClassMap[AbilityRewardRenderUI] = RewardWealthRender;
         View.runtimeClassMap[TPKCHalfRenderUI] = TPKCHalfRender;
         View.runtimeClassMap[TPKCGambleLeftRenderUI] = TPKCGambleLeftRender;
         View.runtimeClassMap[TPKCGambleRightRenderUI] = TPKCGambleRightRender;
         View.runtimeClassMap[AngelFundTitleRenderUI] = AngelFundTitleRender;
         View.runtimeClassMap[SEfaceUI] = SEface;
         View.runtimeClassMap[OlmpicSelCountryRenderUI] = OlmpicSelCountryRender;
         new RegRuntime_LotteryHero();
         new RegRunTime_TeamGuaji();
         new RegRuntime_Commons();
         new RegRuntime_Arena();
         new RegRuntime_Horse();
         new RegRuntime_Shop();
         new RegRuntime_Military();
         new RegRuntime_team();
         new RegRuntime_Chapter();
         new RuntimeChampionship();
         new RegRuntime_Guild();
         new RegRuntime_Mall();
         new RegRunTime_Tools();
         new RegRuntime_Activities();
         new RegRuntime_RecommendHero();
         new RegRuntime_Battlefields();
         new RegRuntime_FamilyBoss();
         new RegRuntime_Vip();
         new RegRuneTime_Auction();
         new RegRuntime_RenZhengs();
         new RegRuntim_QQ();
         new RegRuntime_NewYear();
         new RegRuneTime_HeroAwakenRoad();
         new RegRuntime_XunLeiGift();
         new RegRuntime_Tencent();
         new RegRuntime_Assistant();
         new RegRuntime_FaceBook();
         new RegRunTime_WorldBoss();
         new RegRunTime_Groupon();
         new RegRunTime_Dial();
         new RegRunTime_Day38();
         new RegRuntime_LuckTree();
         new RegRunTime_Pet();
         new RegRunTime_HeroChoose();
         new RegRuntime_Recycle();
         new RegRuntime_busyAcitivitys();
         new RegRuntime_PeakSports();
         this.onComplete();
      }
   }
}
